services:
  - type: web
    name: andd-baay
    env: python
    buildCommand: "pip install -r requirements.txt && python manage.py collectstatic --noinput"
    startCommand: "gunicorn Andd_Baayi.wsgi:application"
    staticPublishPath: staticfiles