services:
  - type: web
    name: andd-baay
    env: python
    buildCommand: "pip install -r requirements.txt && DJANGO_SECRET_KEY=build-time-only python manage.py collectstatic --noinput"
    startCommand: "gunicorn Andd_Baayi.wsgi:application --bind 0.0.0.0:$PORT"
    staticPublishPath: staticfiles
