# Generated by Django 5.1.4 on 2024-12-06 14:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Culture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('periode_recolte', models.CharField(blank=True, max_length=100, null=True)),
                ('duree_avant_recolte', models.IntegerField(blank=True, null=True)),
                ('rendement_moyen', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Localite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, unique=True)),
                ('type_sol', models.CharField(blank=True, max_length=50, null=True)),
                ('conditions_meteo', models.CharField(blank=True, max_length=100, null=True)),
                ('details_meteo', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Utilisateur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, unique=True)),
                ('mot_de_passe', models.TextField()),
                ('type_utilisateur', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Investissement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cout_par_hectare', models.DecimalField(decimal_places=2, max_digits=10)),
                ('autres_frais', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('culture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='baay.culture')),
                ('localite', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='baay.localite')),
            ],
        ),
        migrations.CreateModel(
            name='Projet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('superficie', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date_lancement', models.DateField()),
                ('rendement_estime', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('investissement_total', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('benefices_estimes', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('culture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='baay.culture')),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='baay.utilisateur')),
            ],
        ),
    ]
