# Generated by Django 5.2 on 2026-03-15 21:50

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Localite',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=100, unique=True)),
                ('type_sol', models.CharField(blank=True, max_length=50, null=True)),
                ('conditions_meteo', models.CharField(blank=True, max_length=100, null=True)),
                ('details_meteo', models.TextField(blank=True, null=True)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProduitAgricole',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('saison', models.CharField(blank=True, max_length=50, null=True)),
                ('prix_par_kg', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('apport_nutritionnel', models.TextField(blank=True, null=True)),
                ('quantite_disponible', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('periode_recolte', models.CharField(blank=True, max_length=100, null=True)),
                ('duree_avant_recolte', models.IntegerField(blank=True, null=True)),
                ('rendement_moyen', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('etat', models.CharField(choices=[('En croissance', 'En croissance'), ('Récolté', 'Récolté'), ('Problème', 'Problème'), ('Autre', 'Autre')], default='En croissance', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='PhotoProduitAgricole',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('image', models.ImageField(upload_to='produits_photos/')),
                ('description', models.TextField(blank=True, null=True)),
                ('date_ajout', models.DateTimeField(auto_now_add=True)),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='baay.produitagricole')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('phone_number', models.CharField(blank=True, max_length=15, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('last_login', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Projet',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=200)),
                ('statut', models.CharField(choices=[('en_cours', 'En cours'), ('en_pause', 'En pause'), ('fini', 'Fini')], default='en_cours', max_length=20)),
                ('superficie', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date_lancement', models.DateField()),
                ('rendement_estime', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('culture', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='baay.produitagricole')),
                ('localite', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='baay.localite')),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='baay.profile')),
            ],
        ),
        migrations.CreateModel(
            name='PredictionRendement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rendement_estime', models.FloatField()),
                ('date_prediction', models.DateTimeField(auto_now_add=True)),
                ('projet', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='prediction', to='baay.projet')),
            ],
        ),
        migrations.CreateModel(
            name='Investissement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('description', models.TextField(null=True)),
                ('cout_par_hectare', models.DecimalField(decimal_places=2, max_digits=10)),
                ('autres_frais', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True)),
                ('date_investissement', models.DateField(default=django.utils.timezone.now)),
                ('projet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='baay.projet')),
            ],
        ),
        migrations.CreateModel(
            name='ProjetProduit',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('quantite_semences', models.DecimalField(blank=True, decimal_places=2, help_text='Quantite de semences en kg', max_digits=10, null=True)),
                ('superficie_allouee', models.DecimalField(blank=True, decimal_places=2, help_text='Superficie allouee a ce produit en hectares', max_digits=10, null=True)),
                ('date_semis', models.DateField(blank=True, help_text='Date du semis', null=True)),
                ('date_recolte_prevue', models.DateField(blank=True, help_text='Date de recolte prevue', null=True)),
                ('rendement_final', models.DecimalField(blank=True, decimal_places=2, help_text='Rendement final obtenu en kg', max_digits=10, null=True)),
                ('date_recolte_effective', models.DateField(blank=True, help_text='Date de recolte effective', null=True)),
                ('notes', models.TextField(blank=True, help_text='Notes et observations', null=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projet_produits', to='baay.produitagricole')),
                ('projet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projet_produits', to='baay.projet')),
            ],
            options={
                'verbose_name': 'Produit du Projet',
                'verbose_name_plural': 'Produits du Projet',
                'ordering': ['-date_creation'],
                'unique_together': {('projet', 'produit')},
            },
        ),
        migrations.AddField(
            model_name='projet',
            name='produits',
            field=models.ManyToManyField(related_name='projets_multi', through='baay.ProjetProduit', to='baay.produitagricole'),
        ),
    ]
