# Generated by Django 5.2 on 2026-03-21 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baay', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='projetproduit',
            name='age_plant',
            field=models.IntegerField(blank=True, help_text='Age du plant (ex: en jours)', null=True),
        ),
        migrations.AddField(
            model_name='projetproduit',
            name='image',
            field=models.ImageField(blank=True, help_text='Photo du plant', null=True, upload_to='plants_photos/'),
        ),
    ]
