# Generated by Django 5.1.4 on 2024-12-07 13:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baay', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FruitLegume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='utilisateur',
            name='date_creation',
            field=models.DateTimeField(default=datetime.datetime.utcnow),
        ),
        migrations.AddField(
            model_name='utilisateur',
            name='email',
            field=models.EmailField(default='unknown@example.com', max_length=254, unique=True),
        ),
    ]
