# Generated by Django 5.1.4 on 2024-12-07 15:44

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baay', '0002_fruitlegume_utilisateur_date_creation_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='utilisateur',
            name='type_utilisateur',
        ),
        migrations.AddField(
            model_name='utilisateur',
            name='prenom',
            field=models.CharField(default=' alexandra', max_length=100),
        ),
        migrations.AlterField(
            model_name='utilisateur',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
