# Generated by Django 5.2 on 2026-03-22 10:14

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baay', '0002_projetproduit_age_plant_projetproduit_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pays',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=100, unique=True)),
                ('code_iso', models.CharField(blank=True, max_length=5, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='localite',
            name='pays',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='localites', to='baay.pays'),
        ),
        migrations.AddField(
            model_name='projet',
            name='pays',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='baay.pays'),
        ),
    ]
