# Generated by Django 5.2 on 2026-04-11 11:22

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baay', '0003_pays_localite_pays_projet_pays'),
    ]

    operations = [
        migrations.AddField(
            model_name='predictionrendement',
            name='indice_confiance',
            field=models.FloatField(blank=True, help_text='Indice de confiance du modèle ML (pourcentage)', null=True),
        ),
        migrations.AlterField(
            model_name='localite',
            name='type_sol',
            field=models.CharField(blank=True, choices=[('Dior', 'Dior (Sableux - arachide, niébé)'), ('Deck', 'Deck (Argileux - riz, sorgho)'), ('Deck-Dior', 'Deck-Dior (Mixte - mil, maïs)'), ('Sablonneux', 'Sablonneux (Maraîchage)'), ('Autre', 'Autre')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='projetproduit',
            name='quantite_semences',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Quantite de semences en kg', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0.1)]),
        ),
        migrations.AlterField(
            model_name='projetproduit',
            name='superficie_allouee',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Superficie allouee a ce produit en hectares', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0.01)]),
        ),
        migrations.CreateModel(
            name='ParametresCulture',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('besoin_eau_mm', models.DecimalField(decimal_places=2, help_text='Besoin en eau par cycle (mm)', max_digits=6)),
                ('cycle_croissance_jours', models.IntegerField(help_text='Durée moyenne de la croissance (jours)')),
                ('temperature_min', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('temperature_max', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('produit', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='parametres', to='baay.produitagricole')),
            ],
        ),
        migrations.CreateModel(
            name='HistoriqueRendement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('annee', models.IntegerField(help_text='Année de la récolte')),
                ('rendement_reel_kg_ha', models.DecimalField(decimal_places=2, help_text='Rendement réel obtenu (kg/hectare)', max_digits=10)),
                ('pluviometrie_mm', models.DecimalField(blank=True, decimal_places=2, help_text='Pluviométrie enregistrée cette année-là (mm)', max_digits=6, null=True)),
                ('localite', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historiques', to='baay.localite')),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historiques', to='baay.produitagricole')),
            ],
            options={
                'verbose_name_plural': 'Historiques de Rendement',
                'unique_together': {('localite', 'produit', 'annee')},
            },
        ),
    ]
