# Generated by Django 5.1.4 on 2025-01-09 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("baay", "0003_profile_email_profile_first_name_profile_last_login_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="reset_token",
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
