# Generated by Django 5.2 on 2026-04-11 11:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baay', '0004_predictionrendement_indice_confiance_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='predictionrendement',
            name='projet',
        ),
        migrations.AddField(
            model_name='localite',
            name='pluviometrie_moyenne',
            field=models.FloatField(blank=True, help_text='Pluviométrie moyenne annuelle/saisonnière (mm)', null=True),
        ),
        migrations.AddField(
            model_name='produitagricole',
            name='besoin_eau_mm',
            field=models.FloatField(blank=True, help_text='Besoin en eau total pour le cycle (mm)', null=True),
        ),
        migrations.AddField(
            model_name='produitagricole',
            name='cycle_culture_jours',
            field=models.IntegerField(blank=True, help_text='Durée moyenne entre semis et récolte (jours)', null=True),
        ),
        migrations.AddField(
            model_name='produitagricole',
            name='rendement_potentiel_max',
            field=models.FloatField(blank=True, help_text='Rendement record possible (kg/ha)', null=True),
        ),
        migrations.AddField(
            model_name='projet',
            name='irrigation_disponible',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='projet',
            name='type_engrais',
            field=models.CharField(blank=True, help_text='Ex: NPK, Urée, Organique', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='projet',
            name='utilise_engrais',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='localite',
            name='type_sol',
            field=models.CharField(blank=True, choices=[('Dior', 'Dior'), ('Deck', 'Deck'), ('Deck-Dior', 'Deck-Dior'), ('Sablonneux', 'Sablonneux'), ('Latéritique', 'Latéritique')], max_length=50, null=True),
        ),
        migrations.CreateModel(
            name='PrevisionRecolte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rendement_estime_min', models.FloatField(default=0)),
                ('rendement_estime_max', models.FloatField(default=0)),
                ('indice_confiance', models.FloatField(blank=True, help_text='Indice de confiance du modèle IA (pourcentage)', null=True)),
                ('date_recolte_prevue', models.DateField(blank=True, null=True)),
                ('date_prediction', models.DateTimeField(auto_now_add=True)),
                ('projet', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='prevision', to='baay.projet')),
            ],
        ),
        migrations.DeleteModel(
            name='ParametresCulture',
        ),
        migrations.DeleteModel(
            name='PredictionRendement',
        ),
    ]
