# Generated by Django 5.1.4 on 2025-01-11 15:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("baay", "0004_profile_reset_token"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="fruitlegume",
            name="date_ajout",
        ),
        migrations.RemoveField(
            model_name="profile",
            name="reset_token",
        ),
        migrations.AddField(
            model_name="culture",
            name="fruit_legume",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="baay.fruitlegume",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="projet",
            name="investissement",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="baay.investissement",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="fruitlegume",
            name="apport_nutritionnel",
            field=models.TextField(blank=True, default="", null=True),
        ),
        migrations.AlterField(
            model_name="fruitlegume",
            name="description",
            field=models.TextField(blank=True, default="", null=True),
        ),
        migrations.AlterField(
            model_name="fruitlegume",
            name="prix_par_kg",
            field=models.DecimalField(
                blank=True, decimal_places=2, default=0, max_digits=10, null=True
            ),
        ),
        migrations.AlterField(
            model_name="fruitlegume",
            name="quantite_disponible",
            field=models.DecimalField(
                blank=True, decimal_places=2, default="", max_digits=10, null=True
            ),
        ),
        migrations.AlterField(
            model_name="fruitlegume",
            name="saison",
            field=models.CharField(blank=True, default="", max_length=50, null=True),
        ),
    ]
