# Generated by Django 5.2 on 2026-04-11 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baay', '0005_remove_predictionrendement_projet_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projet',
            name='irrigation_disponible',
        ),
        migrations.RemoveField(
            model_name='projet',
            name='utilise_engrais',
        ),
        migrations.AddField(
            model_name='projet',
            name='type_irrigation',
            field=models.CharField(choices=[('Aucune', 'Aucune (Pluvial)'), ('Goutte-à-goutte', 'Goutte-à-goutte'), ('Aspersion', 'Aspersion'), ('Gravitaire', 'Gravitaire (Canaux)'), ('Manuelle', 'Manuelle (Arrosoir)')], default='Aucune', max_length=50),
        ),
        migrations.AlterField(
            model_name='projet',
            name='type_engrais',
            field=models.CharField(choices=[('Aucun', 'Aucun (Naturel)'), ('Organique', 'Organique (Fumier, Compost)'), ('Minéral NPK', 'Minéral (NPK)'), ('Minéral Urée', 'Minéral (Urée)'), ('Mixte', 'Mixte (Organique + Minéral)')], default='Aucun', max_length=50),
        ),
    ]
