# Generated by Django 5.1.4 on 2025-01-18 12:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("baay", "0006_alter_culture_id_alter_localite_id_alter_profile_id_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="investissement",
            name="culture",
        ),
        migrations.RemoveField(
            model_name="projet",
            name="benefices_estimes",
        ),
        migrations.RemoveField(
            model_name="projet",
            name="investissement",
        ),
        migrations.RemoveField(
            model_name="projet",
            name="investissement_total",
        ),
        migrations.AddField(
            model_name="investissement",
            name="projet",
            field=models.ForeignKey(
                default=1, on_delete=django.db.models.deletion.CASCADE, to="baay.projet"
            ),
            preserve_default=False,
        ),
    ]
