# Generated by Django 5.2 on 2026-04-11 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baay', '0006_remove_projet_irrigation_disponible_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='projet',
            name='image_fond',
            field=models.ImageField(blank=True, help_text='Image de couverture du projet (optionnelle)', null=True, upload_to='projets_fonds/'),
        ),
    ]
