# Generated by Django 5.2 on 2026-04-25 12:34

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baay', '0007_projet_image_fond'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ferme',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('superficie_totale', models.DecimalField(blank=True, decimal_places=2, help_text='Superficie totale de la ferme en hectares', max_digits=10, null=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('localite', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='baay.localite')),
                ('pays', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='baay.pays')),
                ('proprietaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fermes', to='baay.profile')),
            ],
            options={
                'ordering': ['-date_creation'],
            },
        ),
        migrations.AddField(
            model_name='projet',
            name='ferme',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='projets', to='baay.ferme'),
        ),
        migrations.CreateModel(
            name='MembreFerme',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('role', models.CharField(choices=[('proprietaire', 'Propriétaire'), ('manager', 'Manager'), ('technicien', 'Technicien'), ('ouvrier', 'Ouvrier')], default='ouvrier', max_length=20)),
                ('date_ajout', models.DateTimeField(auto_now_add=True)),
                ('ferme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='membres', to='baay.ferme')),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fermes_membre', to='baay.profile')),
            ],
            options={
                'unique_together': {('ferme', 'utilisateur')},
            },
        ),
    ]
