# Generated by Django 5.1.4 on 2025-01-18 12:55

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("baay", "0007_remove_investissement_culture_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProduitAgricole",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("nom", models.CharField(max_length=100, unique=True)),
                ("description", models.TextField(blank=True, null=True)),
                ("saison", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "prix_par_kg",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("apport_nutritionnel", models.TextField(blank=True, null=True)),
                (
                    "quantite_disponible",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "periode_recolte",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("duree_avant_recolte", models.IntegerField(blank=True, null=True)),
                (
                    "rendement_moyen",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
            ],
        ),
        migrations.RemoveField(
            model_name="culture",
            name="fruit_legume",
        ),
        migrations.AlterField(
            model_name="projet",
            name="culture",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="baay.produitagricole"
            ),
        ),
        migrations.DeleteModel(
            name="FruitLegume",
        ),
        migrations.DeleteModel(
            name="Culture",
        ),
    ]
