# Generated by Django 5.1.4 on 2025-01-19 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("baay", "0008_produitagricole_remove_culture_fruit_legume_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="projet",
            name="statut",
            field=models.TextField(blank=True, null=True),
        ),
    ]
