# Generated by Django 5.1.4 on 2025-01-20 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("baay", "0009_projet_statut"),
    ]

    operations = [
        migrations.AddField(
            model_name="localite",
            name="latitude",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="localite",
            name="longitude",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="produitagricole",
            name="photo",
            field=models.ImageField(blank=True, null=True, upload_to="produits/"),
        ),
    ]
