# Generated by Django 5.1.4 on 2025-01-20 14:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("baay", "0010_localite_latitude_localite_longitude_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="projet",
            name="localite",
            field=models.ForeignKey(
                default="b37e9b5f2b00463db21fe0a6f207a338",
                on_delete=django.db.models.deletion.CASCADE,
                to="baay.localite",
            ),
        ),
    ]
