# Generated by Django 5.2.13 on 2026-04-25 21:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('baay', '0009_projet_ferme_required'),
        ('baay', '0011_membreferme_peut_gerer_membres'),
    ]

    operations = [
    ]
