# Generated by Django 5.1.4 on 2025-03-03 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("baay", "0012_remove_investissement_autres_frais_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="projet",
            name="nom",
            field=models.CharField(default="culture", max_length=200),
            preserve_default=False,
        ),
    ]
