# Generated by Django 5.1.4 on 2025-03-08 20:01

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("baay", "0013_projet_nom"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="profile",
            name="email",
        ),
        migrations.RemoveField(
            model_name="profile",
            name="first_name",
        ),
        migrations.RemoveField(
            model_name="profile",
            name="last_name",
        ),
        migrations.AddField(
            model_name="investissement",
            name="autres_frais",
            field=models.DecimalField(
                blank=True, decimal_places=2, default=0, max_digits=10, null=True
            ),
        ),
        migrations.AlterField(
            model_name="investissement",
            name="id",
            field=models.UUIDField(
                default=uuid.uuid4, editable=False, primary_key=True, serialize=False
            ),
        ),
        migrations.AlterField(
            model_name="produitagricole",
            name="photo",
            field=models.ImageField(blank=True, null=True, upload_to="produits/"),
        ),
        migrations.AlterField(
            model_name="projet",
            name="localite",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="baay.localite"
            ),
        ),
        migrations.AlterField(
            model_name="projet",
            name="statut",
            field=models.CharField(
                choices=[
                    ("en_cours", "En cours"),
                    ("en_pause", "En pause"),
                    ("fini", "Fini"),
                ],
                default="en_cours",
                max_length=20,
            ),
        ),
    ]
