# Generated by Django 5.1.4 on 2025-03-08 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("baay", "0014_remove_profile_email_remove_profile_first_name_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="produitagricole",
            name="photo",
        ),
        migrations.AlterField(
            model_name="produitagricole",
            name="id",
            field=models.UUIDField(editable=False, primary_key=True, serialize=False),
        ),
    ]
