# Generated by Django 5.1.4 on 2025-03-08 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("baay", "0015_remove_produitagricole_photo_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="produitagricole",
            name="etat",
            field=models.CharField(
                choices=[
                    ("en_croissance", "En croissance"),
                    ("récolté", "Récolté"),
                    ("problème", "Problème"),
                ],
                default="en_croissance",
                max_length=100,
            ),
        ),
    ]
