# Generated by Django 5.1.4 on 2025-03-09 12:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("baay", "0016_produitagricole_etat"),
    ]

    operations = [
        migrations.CreateModel(
            name="PredictionRendement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("rendement_estime", models.FloatField()),
                ("date_prediction", models.DateTimeField(auto_now_add=True)),
                (
                    "projet",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="prediction",
                        to="baay.projet",
                    ),
                ),
            ],
        ),
    ]
