# Generated by Django 5.2 on 2026-04-27 21:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('baay', '0017_ferme_latitude_longitude'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='tache',
            new_name='baay_tache_ferme_i_e4cbc7_idx',
            old_name='baay_tache_ferme_i_idx',
        ),
        migrations.RenameIndex(
            model_name='tache',
            new_name='baay_tache_assigne_5a4903_idx',
            old_name='baay_tache_assigne_idx',
        ),
    ]
