# Generated by Django 5.1.4 on 2025-03-09 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("baay", "0017_predictionrendement"),
    ]

    operations = [
        migrations.AlterField(
            model_name="produitagricole",
            name="etat",
            field=models.CharField(
                choices=[
                    ("En croissance", "bg-success"),
                    ("Récolté", "bg-primary"),
                    ("Problème", "bg-danger"),
                    ("Autre", "bg-secondary"),
                ],
                default="En croissance",
                max_length=100,
            ),
        ),
    ]
