# Generated by Django 5.2 on 2025-04-11 08:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baay', '0018_alter_produitagricole_etat'),
    ]

    operations = [
        migrations.CreateModel(
            name='DonneePrediction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('superficie', models.DecimalField(decimal_places=2, max_digits=10)),
                ('prix_par_kg', models.DecimalField(decimal_places=2, max_digits=10)),
                ('duree_avant_recolte', models.IntegerField()),
                ('type_sol', models.CharField(max_length=100)),
                ('conditions_meteo', models.CharField(max_length=100)),
                ('investissement_total', models.DecimalField(decimal_places=2, max_digits=12)),
                ('rendement_estime', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('projet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='donnees_prediction', to='baay.projet')),
            ],
        ),
    ]
