# Generated by Django 5.2 on 2025-04-11 08:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baay', '0019_donneeprediction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donneeprediction',
            name='projet',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='donnees_prediction', to='baay.projet'),
        ),
    ]
