# Generated by Django 5.2 on 2025-04-11 10:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('baay', '0020_alter_donneeprediction_projet'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DonneePrediction',
        ),
    ]
