# Generated by Django 5.2 on 2025-04-29 15:59

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baay', '0021_delete_donneeprediction'),
    ]

    operations = [
        migrations.CreateModel(
            name='PhotoProduitAgricole',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('image', models.ImageField(upload_to='produits_photos/')),
                ('description', models.TextField(blank=True, null=True)),
                ('date_ajout', models.DateTimeField(auto_now_add=True)),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='baay.produitagricole')),
            ],
        ),
    ]
