# Generated by Django 5.2 on 2026-03-09 20:45

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baay', '0022_photoproduitagricole'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produitagricole',
            name='etat',
            field=models.CharField(choices=[('En croissance', 'En croissance'), ('Récolté', 'Récolté'), ('Problème', 'Problème'), ('Autre', 'Autre')], default='En croissance', max_length=100),
        ),
        migrations.AlterField(
            model_name='produitagricole',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
