# Generated by Codex on 2026-03-14
#
# This resolves the migration graph conflict introduced by two concurrent
# leaf migrations both numbered 0023.

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("baay", "0023_alter_produitagricole_etat_alter_produitagricole_id"),
        ("baay", "0023_semis"),
    ]

    operations = []

