# Generated by Codex on 2026-03-14

import uuid
from django.db import migrations, models
import django.db.models.deletion


def backfill_projetproduit(apps, schema_editor):
    Projet = apps.get_model("baay", "Projet")
    ProjetProduit = apps.get_model("baay", "ProjetProduit")

    # For existing projects that only have `culture` set, create a through row
    # so the new semis/projet_produits views can work without manual re-entry.
    for projet in Projet.objects.exclude(culture__isnull=True):
        if not ProjetProduit.objects.filter(projet_id=projet.id, produit_id=projet.culture_id).exists():
            ProjetProduit.objects.create(projet_id=projet.id, produit_id=projet.culture_id)


class Migration(migrations.Migration):
    dependencies = [
        ("baay", "0024_merge_0023_semis_and_0023_produitagricole"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProjetProduit",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("quantite_semences", models.DecimalField(blank=True, decimal_places=2, help_text="Quantite de semences en kg", max_digits=10, null=True)),
                ("superficie_allouee", models.DecimalField(blank=True, decimal_places=2, help_text="Superficie allouee a ce produit en hectares", max_digits=10, null=True)),
                ("date_semis", models.DateField(blank=True, help_text="Date du semis", null=True)),
                ("date_recolte_prevue", models.DateField(blank=True, help_text="Date de recolte prevue", null=True)),
                ("rendement_final", models.DecimalField(blank=True, decimal_places=2, help_text="Rendement final obtenu en kg", max_digits=10, null=True)),
                ("date_recolte_effective", models.DateField(blank=True, help_text="Date de recolte effective", null=True)),
                ("notes", models.TextField(blank=True, help_text="Notes et observations", null=True)),
                ("date_creation", models.DateTimeField(auto_now_add=True)),
                ("date_modification", models.DateTimeField(auto_now=True)),
                ("produit", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="projet_produits", to="baay.produitagricole")),
                ("projet", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="projet_produits", to="baay.projet")),
            ],
            options={
                "verbose_name": "Produit du Projet",
                "verbose_name_plural": "Produits du Projet",
                "ordering": ["-date_creation"],
                "unique_together": {("projet", "produit")},
            },
        ),
        migrations.AddField(
            model_name="projet",
            name="produits",
            field=models.ManyToManyField(related_name="projets_multi", through="baay.ProjetProduit", to="baay.produitagricole"),
        ),
        migrations.RunPython(backfill_projetproduit, reverse_code=migrations.RunPython.noop),
    ]

