# Generated by Django 5.2 on 2026-05-02 11:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('baay', '0024_previsionrecolte_projet_produit'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='message',
            new_name='baay_messag_convers_5b32f3_idx',
            old_name='baay_message_convers_d3c3e4_idx',
        ),
        migrations.RenameIndex(
            model_name='message',
            new_name='baay_messag_expedit_770353_idx',
            old_name='baay_message_expedit_c3a5e4_idx',
        ),
        migrations.RenameIndex(
            model_name='messagereaction',
            new_name='baay_messag_message_7108b3_idx',
            old_name='baay_messag_message_emoji_idx',
        ),
    ]
