# Generated by Django 5.2.13 on 2026-05-02 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baay', '0025_rename_baay_message_convers_d3c3e4_idx_baay_messag_convers_5b32f3_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='onboarding_completed',
            field=models.BooleanField(default=False, help_text="True lorsque l'utilisateur a terminé ou ignoré l'assistant de première connexion."),
        ),
    ]
