# Generated by Django 5.2 on 2026-05-02 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baay', '0026_profile_onboarding_completed'),
    ]

    operations = [
        migrations.AddField(
            model_name='projet',
            name='budget_alloue',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Budget prévisionnel total du projet (FCFA). Utilisé pour les alertes de dépassement.', max_digits=14, null=True),
        ),
    ]
