# Generated by Django 5.2.13 on 2026-05-02 21:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baay', '0027_projet_budget_alloue'),
    ]

    operations = [
        migrations.AddField(
            model_name='investissement',
            name='projet_produit',
            field=models.ForeignKey(blank=True, help_text='Si vide : dépense générale au niveau projet. Sinon : affectée à cette culture.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='investissements', to='baay.projetproduit'),
        ),
        migrations.AddField(
            model_name='projetproduit',
            name='budget_alloue',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Budget optionnel alloué à cette culture (FCFA), pour alertes par produit.', max_digits=14, null=True),
        ),
    ]
