# Generated by Django 5.2 on 2026-05-03 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baay', '0029_investissement_libelle_categorie'),
    ]

    operations = [
        migrations.AddField(
            model_name='projet',
            name='date_fin',
            field=models.DateField(blank=True, help_text='Date de fin prévue/réelle du projet', null=True),
        ),
    ]
