# Generated by Django 5.2 on 2026-05-03 14:00

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baay', '0030_projet_date_fin'),
    ]

    operations = [
        migrations.AddField(
            model_name='investissement',
            name='date_verrouillage',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='investissement',
            name='verrouille',
            field=models.BooleanField(default=False, help_text='Bloque la modification apres cloture du projet.'),
        ),
        migrations.CreateModel(
            name='Recette',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('produit_vendu', models.CharField(blank=True, max_length=150)),
                ('quantite_vendue', models.DecimalField(decimal_places=2, max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('unite', models.CharField(choices=[('kg', 'Kg'), ('tonne', 'Tonne'), ('sac', 'Sac')], default='kg', max_length=16)),
                ('prix_unitaire', models.DecimalField(decimal_places=2, max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('montant_total', models.DecimalField(decimal_places=2, editable=False, max_digits=18)),
                ('date_encaissement', models.DateField(default=django.utils.timezone.now)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('projet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recettes', to='baay.projet')),
                ('projet_produit', models.ForeignKey(blank=True, help_text='Culture vendue lorsque la recette est liee a une ligne de projet.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recettes', to='baay.projetproduit')),
            ],
            options={
                'ordering': ['-date_encaissement', '-date_creation'],
                'indexes': [models.Index(fields=['projet', 'date_encaissement'], name='baay_recett_projet__5d6eb7_idx'), models.Index(fields=['projet_produit'], name='baay_recett_projet__8380f9_idx')],
            },
        ),
    ]
