# Generated by Django 5.2 on 2026-05-03 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("baay", "0033_projet_taux_avancement_personnalise"),
    ]

    operations = [
        migrations.AlterField(
            model_name="projet",
            name="type_engrais",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Aucun", "Aucun (Naturel)"),
                    ("Organique", "Organique (Fumier, Compost)"),
                    ("Minéral NPK", "Minéral (NPK)"),
                    ("Minéral Urée", "Minéral (Urée)"),
                    ("Mixte", "Mixte (Organique + Minéral)"),
                ],
                default="Aucun",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="projet",
            name="type_irrigation",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Aucune", "Aucune (Pluvial)"),
                    ("Goutte-à-goutte", "Goutte-à-goutte"),
                    ("Aspersion", "Aspersion"),
                    ("Gravitaire", "Gravitaire (Canaux)"),
                    ("Manuelle", "Manuelle (Arrosoir)"),
                ],
                default="Aucune",
                max_length=50,
            ),
        ),
    ]
