# Generated by Django 5.2.14 on 2026-05-06 16:35

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baay', '0037_historiquesol'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='historiquesol',
            new_name='baay_histor_ferme_i_fa5e7d_idx',
            old_name='baay_histor_ferme_i_date_idx',
        ),
        migrations.RenameIndex(
            model_name='recette',
            new_name='baay_recett_projet__9c8884_idx',
            old_name='baay_recett_projet__dv_idx',
        ),
        migrations.AlterField(
            model_name='depense',
            name='justificatif',
            field=cloudinary.models.CloudinaryField(blank=True, help_text='Justificatif (photo / scan — léger pour le mobile)', max_length=255, null=True, verbose_name='justificatif'),
        ),
        migrations.AlterField(
            model_name='ferme',
            name='image_couverture',
            field=cloudinary.models.CloudinaryField(blank=True, help_text='Photo principale / vue de la ferme', max_length=255, null=True, verbose_name='image_couverture'),
        ),
        migrations.AlterField(
            model_name='ferme',
            name='image_infrastructure',
            field=cloudinary.models.CloudinaryField(blank=True, help_text='Photo des infrastructures ou équipements (optionnel)', max_length=255, null=True, verbose_name='image_infrastructure'),
        ),
        migrations.AlterField(
            model_name='investissement',
            name='piece_justificative',
            field=cloudinary.models.CloudinaryField(blank=True, help_text='Justificatif (scan photo ou PDF — optimisé côté Cloudinary pour images)', max_length=255, null=True, verbose_name='piece_justificative'),
        ),
        migrations.AlterField(
            model_name='membreferme',
            name='photo_profil',
            field=cloudinary.models.CloudinaryField(blank=True, help_text='Photo du collaborateur (membre de la ferme)', max_length=255, null=True, verbose_name='photo_profil'),
        ),
        migrations.AlterField(
            model_name='message',
            name='piece_jointe',
            field=cloudinary.models.CloudinaryField(blank=True, help_text='Pièce jointe (photo optimisée ou document)', max_length=255, null=True, verbose_name='piece_jointe'),
        ),
        migrations.AlterField(
            model_name='projet',
            name='image_fond',
            field=cloudinary.models.CloudinaryField(blank=True, help_text='Image de couverture du projet (optionnelle)', max_length=255, null=True, verbose_name='image_fond'),
        ),
        migrations.AlterField(
            model_name='projet',
            name='statut',
            field=models.CharField(choices=[('en_cours', 'En cours'), ('en_pause', 'En pause'), ('fini', 'Fini'), ('cloture', 'Clôturé')], default='en_cours', max_length=20),
        ),
        migrations.AlterField(
            model_name='projetproduit',
            name='image',
            field=cloudinary.models.CloudinaryField(blank=True, help_text='Photo du plant', max_length=255, null=True, verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='recette',
            name='justificatif_facture',
            field=cloudinary.models.CloudinaryField(blank=True, help_text='Justificatif de vente (facture ou photo pesée)', max_length=255, null=True, verbose_name='justificatif_facture'),
        ),
    ]
