# Generated by Django 5.2 on 2026-05-11 16:35

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baay', '0041_geo_marketplace_models'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='documentconnaissance',
            new_name='baay_docume_categor_d40d02_idx',
            old_name='baay_documen_categor_a1b2c3_idx',
        ),
        migrations.RenameIndex(
            model_name='documentconnaissance',
            new_name='baay_docume_mots_cl_089f7a_idx',
            old_name='baay_documen_mots_cl_d4e5f6_idx',
        ),
        migrations.RenameIndex(
            model_name='incidentrapporte',
            new_name='baay_incide_ferme_i_5b9230_idx',
            old_name='baay_inciden_ferme_i_8f3d2e_idx',
        ),
        migrations.RenameIndex(
            model_name='incidentrapporte',
            new_name='baay_incide_type_in_239665_idx',
            old_name='baay_inciden_type_in_5e7a9b_idx',
        ),
        migrations.RenameIndex(
            model_name='incidentrapporte',
            new_name='baay_incide_signale_81834d_idx',
            old_name='baay_inciden_signale_e2f1c8_idx',
        ),
        migrations.RenameIndex(
            model_name='offreproduit',
            new_name='baay_offrep_produit_3e42ee_idx',
            old_name='baay_offrepr_produit_9f8a2b_idx',
        ),
        migrations.RenameIndex(
            model_name='offreproduit',
            new_name='baay_offrep_vendeur_5d5ecc_idx',
            old_name='baay_offrepr_vendeur_5c7d3e_idx',
        ),
        migrations.RenameIndex(
            model_name='offreproduit',
            new_name='baay_offrep_localit_ce170d_idx',
            old_name='baay_offrepr_localit_1e6b4c_idx',
        ),
        migrations.RenameIndex(
            model_name='offreproduit',
            new_name='baay_offrep_qualite_39155c_idx',
            old_name='baay_offrepr_qualite_2d8e7f_idx',
        ),
        migrations.RenameIndex(
            model_name='recette',
            new_name='baay_recett_statut__ec8608_idx',
            old_name='baay_recett_statut__5f8a1b_idx',
        ),
        migrations.RenameIndex(
            model_name='recette',
            new_name='baay_recett_projet__03068b_idx',
            old_name='baay_recett_projet__8c9d2e_idx',
        ),
        migrations.RenameIndex(
            model_name='recommandationfertilisation',
            new_name='baay_recomm_histori_666c20_idx',
            old_name='baay_recomm_histor_7d9c2a_idx',
        ),
        migrations.RenameIndex(
            model_name='recommandationfertilisation',
            new_name='baay_recomm_culture_5d7da1_idx',
            old_name='baay_recomm_culture_9e8b1c_idx',
        ),
        migrations.RenameIndex(
            model_name='simulationroi',
            new_name='baay_simula_projet__24aebe_idx',
            old_name='baay_simula_projet__3d4e5f_idx',
        ),
        migrations.RenameIndex(
            model_name='simulationroi',
            new_name='baay_simula_cree_pa_f09a06_idx',
            old_name='baay_simula_cree_pa_6g7h8i_idx',
        ),
        migrations.RenameIndex(
            model_name='transactionmarche',
            new_name='baay_transa_offre_i_513d97_idx',
            old_name='baay_transac_offre_i_4f7g8h_idx',
        ),
        migrations.RenameIndex(
            model_name='transactionmarche',
            new_name='baay_transa_acheteu_96935f_idx',
            old_name='baay_transac_acheteu_6i9j0k_idx',
        ),
        migrations.RenameIndex(
            model_name='transactionmarche',
            new_name='baay_transa_statut_0f76d8_idx',
            old_name='baay_transac_statut_8m1n2o_idx',
        ),
        migrations.AlterField(
            model_name='incidentrapporte',
            name='gravite_detectee',
            field=models.CharField(choices=[('faible', 'Faible - À surveiller'), ('moyenne', 'Moyenne - Action nécessaire'), ('haute', 'Haute - Urgent'), ('critique', 'Critique - Danger immédiat')], default='moyenne', help_text="Gravité estimée par l'IA ou l'utilisateur", max_length=10),
        ),
        migrations.AlterField(
            model_name='incidentrapporte',
            name='type_incident',
            field=models.CharField(choices=[('invasion_ravageurs', 'Invasion de ravageurs (criquets, chenilles...)'), ('maladie_feuilles', 'Maladie des feuilles'), ('maladie_racines', 'Maladie des racines/tiges'), ('stress_hydrique', 'Stress hydrique / Sécheresse'), ('inondation', "Inondation / Excès d'eau"), ('vol', 'Vol / Intrusion'), ('incident_materiel', 'Incident matériel / Dégâts'), ('autre', 'Autre incident')], help_text="Catégorie de l'incident détectée", max_length=30),
        ),
        migrations.AlterField(
            model_name='offreproduit',
            name='quantite_disponible',
            field=models.DecimalField(decimal_places=2, help_text='Quantité disponible (kg)', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))]),
        ),
        migrations.AlterField(
            model_name='recommandationfertilisation',
            name='type_engrais_conseille',
            field=models.CharField(choices=[('organique', 'Organique (Compost, Fumier)'), ('mineral_npk', 'Minéral NPK'), ('mineral_uree', 'Minéral (Urée)'), ('mixte', 'Mixte (Organique + Minéral)'), ('aucun', 'Aucun - Sol équilibré')], help_text="Type d'engrais recommandé", max_length=20),
        ),
        migrations.AlterField(
            model_name='transactionmarche',
            name='quantite_achetee',
            field=models.DecimalField(decimal_places=2, help_text='Quantité finalement achetée', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))]),
        ),
    ]
