# Generated by Django 5.2 on 2026-05-14 22:00

import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baay', '0042_rename_baay_documen_categor_a1b2c3_idx_baay_docume_categor_d40d02_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='membreferme',
            name='date_expiration',
            field=models.DateTimeField(blank=True, help_text="Date d'expiration de l'accès (pour les rôles temporaires).", null=True),
        ),
        migrations.AlterField(
            model_name='membreferme',
            name='role',
            field=models.CharField(choices=[('manager', 'Manager'), ('technicien', 'Technicien'), ('ouvrier', 'Ouvrier'), ('consultant', 'Consultant'), ('invite', 'Invité')], default='ouvrier', max_length=20),
        ),
        migrations.CreateModel(
            name='NoteAgronomique',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('contenu', models.TextField(help_text='Contenu de la note ou du commentaire agronomique')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('auteur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes_agronomiques', to='baay.profile')),
                ('projet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes_agronomiques', to='baay.projet')),
            ],
            options={
                'verbose_name': 'Note agronomique',
                'verbose_name_plural': 'Notes agronomiques',
                'ordering': ['-date_creation'],
            },
        ),
        migrations.CreateModel(
            name='StockIntrant',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nom', models.CharField(help_text="Nom de l'intrant (ex: Urée, Semences de maïs)", max_length=100)),
                ('categorie', models.CharField(choices=[('engrais', 'Engrais'), ('semence', 'Semence'), ('pesticide', 'Pesticide'), ('autre', 'Autre')], default='autre', max_length=20)),
                ('quantite', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('unite', models.CharField(choices=[('kg', 'Kilogrammes'), ('L', 'Litres'), ('sacs', 'Sacs'), ('unites', 'Unités')], default='kg', max_length=10)),
                ('seuil_alerte', models.DecimalField(decimal_places=2, default=Decimal('10.00'), help_text='Seuil en dessous duquel une alerte de stock bas est déclenchée', max_digits=12)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('ferme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='intrants', to='baay.ferme')),
            ],
            options={
                'verbose_name': "Stock d'intrant",
                'verbose_name_plural': "Stocks d'intrants",
                'ordering': ['-date_creation'],
            },
        ),
        migrations.CreateModel(
            name='StockRecolte',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('quantite', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('unite', models.CharField(choices=[('kg', 'Kilogrammes'), ('tonnes', 'Tonnes'), ('sacs', 'Sacs')], default='kg', max_length=10)),
                ('date_recolte', models.DateField(help_text='Date de la récolte')),
                ('qualite', models.CharField(choices=[('A', 'Grade A'), ('B', 'Grade B'), ('C', 'Grade C'), ('D', 'Grade D'), ('NC', 'Non classé')], default='NC', max_length=2)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('ferme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recoltes', to='baay.ferme')),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recoltes_stock', to='baay.produitagricole')),
                ('projet', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recoltes', to='baay.projet')),
            ],
            options={
                'verbose_name': 'Stock de récolte',
                'verbose_name_plural': 'Stocks de récoltes',
                'ordering': ['-date_recolte', '-date_creation'],
            },
        ),
        migrations.CreateModel(
            name='MouvementStock',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('entree', 'Entrée'), ('sortie', 'Sortie')], max_length=10)),
                ('quantite', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('date_mouvement', models.DateTimeField(auto_now_add=True)),
                ('raison', models.CharField(blank=True, help_text='Raison du mouvement (ex: achat, utilisation, vente)', max_length=255)),
                ('ferme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mouvements_stock', to='baay.ferme')),
                ('investissement', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mouvements_stock', to='baay.investissement')),
                ('utilisateur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mouvements_stock', to='baay.profile')),
                ('stock_intrant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mouvements', to='baay.stockintrant')),
                ('stock_recolte', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mouvements', to='baay.stockrecolte')),
            ],
            options={
                'verbose_name': 'Mouvement de stock',
                'verbose_name_plural': 'Mouvements de stock',
                'ordering': ['-date_mouvement'],
            },
        ),
    ]
