# Generated by Codex on 2026-05-17

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("baay", "0043_membreferme_date_expiration_alter_membreferme_role_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="projet",
            name="type_cycle",
            field=models.CharField(
                choices=[
                    ("campagne", "Campagne saisonniere"),
                    ("perenne", "Projet perenne"),
                ],
                default="campagne",
                help_text="Campagne courte (riz, mais...) ou projet perenne avec campagnes successives.",
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="CampagneProjet",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("nom", models.CharField(max_length=120)),
                ("saison", models.CharField(blank=True, default="", max_length=80)),
                ("date_debut", models.DateField()),
                ("date_fin", models.DateField(blank=True, null=True)),
                (
                    "statut",
                    models.CharField(
                        choices=[
                            ("preparation", "Preparation"),
                            ("en_cours", "En cours"),
                            ("fini", "Terminee"),
                        ],
                        default="en_cours",
                        max_length=20,
                    ),
                ),
                (
                    "rendement_total",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Rendement total obtenu pendant cette campagne (kg).",
                        max_digits=12,
                        null=True,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "cout_total",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Cout total estime de cette campagne (FCFA).",
                        max_digits=14,
                        null=True,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "recette_totale",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Recette totale estimee de cette campagne (FCFA).",
                        max_digits=14,
                        null=True,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                ("notes", models.TextField(blank=True, default="")),
                ("date_creation", models.DateTimeField(auto_now_add=True)),
                ("date_modification", models.DateTimeField(auto_now=True)),
                (
                    "campagne_precedente",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="campagnes_suivantes",
                        to="baay.campagneprojet",
                    ),
                ),
                (
                    "projet",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="campagnes",
                        to="baay.projet",
                    ),
                ),
            ],
            options={
                "verbose_name": "Campagne de projet",
                "verbose_name_plural": "Campagnes de projet",
                "ordering": ["-date_debut", "-date_creation"],
            },
        ),
        migrations.AddConstraint(
            model_name="campagneprojet",
            constraint=models.UniqueConstraint(fields=("projet", "nom"), name="unique_campagne_nom_par_projet"),
        ),
        migrations.AddIndex(
            model_name="campagneprojet",
            index=models.Index(fields=["projet", "statut"], name="baay_campag_projet_stat_idx"),
        ),
        migrations.AddIndex(
            model_name="campagneprojet",
            index=models.Index(fields=["projet", "date_debut"], name="baay_campag_projet_debut_idx"),
        ),
    ]
