# Generated by Django 5.2 on 2026-05-20 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baay', '0045_analyseimageculture'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='analyseimageculture',
            new_name='baay_analys_projet__7e53fe_idx',
            old_name='baay_analys_projet__a1b2c3_idx',
        ),
        migrations.AddField(
            model_name='ferme',
            name='subscription_expiration',
            field=models.DateTimeField(blank=True, help_text="Date d'expiration de l'abonnement premium", null=True),
        ),
        migrations.AddField(
            model_name='ferme',
            name='subscription_tier',
            field=models.CharField(choices=[('basic', 'Baay Basique (Gratuit)'), ('pro', 'Baay Pro (SaaS)'), ('coop', 'Baay Coopérative (B2B)')], default='basic', help_text="Niveau d'abonnement de la ferme", max_length=20),
        ),
    ]
