# Generated by Django 5.2.13 on 2026-05-24 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baay', '0046_rename_baay_analys_projet__a1b2c3_idx_baay_analys_projet__7e53fe_idx_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='membreferme',
            index=models.Index(fields=['utilisateur', 'date_expiration'], name='baay_membre_user_expiry_idx'),
        ),
        migrations.AddIndex(
            model_name='membreferme',
            index=models.Index(fields=['ferme', 'date_expiration'], name='baay_membre_ferme_expiry_idx'),
        ),
        migrations.AddIndex(
            model_name='projet',
            index=models.Index(fields=['ferme', 'statut'], name='baay_projet_ferme_stat_idx'),
        ),
        migrations.AddIndex(
            model_name='projet',
            index=models.Index(fields=['utilisateur', 'statut'], name='baay_projet_user_stat_idx'),
        ),
        migrations.AddIndex(
            model_name='projet',
            index=models.Index(fields=['ferme', 'date_lancement'], name='baay_projet_ferme_lanc_idx'),
        ),
    ]
