# Generated by Django 5.2.13 on 2026-05-27 21:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baay', '0050_mlmodeleinfo'),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Commentaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.UUIDField()),
                ('texte', models.TextField(max_length=2000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Commentaire',
                'verbose_name_plural': 'Commentaires',
                'ordering': ['created_at'],
            },
        ),
        migrations.RenameIndex(
            model_name='mlmodeleinfo',
            new_name='baay_mlmode_culture_9067e6_idx',
            old_name='baay_mlmode_culture_date_idx',
        ),
        migrations.RenameIndex(
            model_name='mlmodeleinfo',
            new_name='baay_mlmode_actif_834fb2_idx',
            old_name='baay_mlmode_actif_idx',
        ),
        migrations.RenameIndex(
            model_name='previsionfeatures',
            new_name='baay_previs_date_cr_63ac81_idx',
            old_name='baay_prevfe_date_cr_idx',
        ),
        migrations.RenameIndex(
            model_name='previsionfeatures',
            new_name='baay_previs_rendeme_5f7f44_idx',
            old_name='baay_prevfe_rendem_idx',
        ),
        migrations.AddField(
            model_name='commentaire',
            name='auteur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commentaires', to='baay.profile'),
        ),
        migrations.AddField(
            model_name='commentaire',
            name='content_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
        ),
        migrations.AddIndex(
            model_name='commentaire',
            index=models.Index(fields=['content_type', 'object_id'], name='baay_commen_content_c031ee_idx'),
        ),
    ]
