# Generated by Django 5.2.13 on 2026-05-28 12:05

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baay', '0051_commentaire_generic'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppelAPILog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service', models.CharField(choices=[('gemini', 'Gemini Vision'), ('galsenai', 'GalsenAI (HuggingFace)')], db_index=True, max_length=32)),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('cout_estime_usd', models.DecimalField(decimal_places=6, default=Decimal('0'), max_digits=10)),
                ('cache_hit', models.BooleanField(db_index=True, default=False)),
                ('modele', models.CharField(blank=True, max_length=64)),
                ('duree_ms', models.PositiveIntegerField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Appel API',
                'verbose_name_plural': 'Appels API',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['service', '-timestamp'], name='baay_appela_service_be4a3f_idx'), models.Index(fields=['timestamp', 'cache_hit'], name='baay_appela_timesta_f623c8_idx')],
            },
        ),
    ]
