# Generated by Django 5.2.13 on 2026-05-28 13:12

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baay', '0052_appel_api_log'),
    ]

    operations = [
        migrations.CreateModel(
            name='InvitationFerme',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('token', models.CharField(editable=False, max_length=64, unique=True)),
                ('role_invite', models.CharField(choices=[('technician', 'Technicien'), ('worker', 'Ouvrier')], default='technician', max_length=20)),
                ('email_invite', models.EmailField(blank=True, max_length=254)),
                ('utilisee', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('cree_par', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invitations_creees', to='baay.profile')),
                ('ferme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invitations', to='baay.ferme')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
