# Generated by Django 5.2.13 on 2026-05-28 17:24

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baay', '0053_invitation_ferme'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArticleActualite',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('source', models.CharField(choices=[('anacim', 'ANACIM — Météo & Agroclimat'), ('mae', "Ministère de l'Agriculture"), ('ansd', 'ANSD — Statistiques'), ('fao', 'FAO Sénégal'), ('autre', 'Autre source')], db_index=True, default='autre', max_length=20)),
                ('categorie', models.CharField(choices=[('meteo', 'Météo & Agroclimat'), ('conseil', 'Conseils agricoles'), ('politique', 'Politique agricole'), ('marche', 'Marchés & prix'), ('autre', 'Autre')], db_index=True, default='autre', max_length=20)),
                ('titre', models.CharField(max_length=500)),
                ('resume', models.TextField(blank=True)),
                ('contenu', models.TextField(blank=True)),
                ('url_originale', models.URLField(max_length=2000, unique=True)),
                ('image_url', models.URLField(blank=True, max_length=2000)),
                ('date_publication', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('date_collecte', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('actif', models.BooleanField(db_index=True, default=True, help_text='False = masqué de la liste publique (spam, erreur).')),
            ],
            options={
                'verbose_name': 'Article actualité',
                'verbose_name_plural': 'Articles actualités',
                'ordering': ['-date_publication', '-date_collecte'],
                'indexes': [models.Index(fields=['source', '-date_publication'], name='baay_articl_source_f1551d_idx'), models.Index(fields=['categorie', '-date_publication'], name='baay_articl_categor_6b1aef_idx'), models.Index(fields=['actif', '-date_publication'], name='baay_articl_actif_ad7156_idx')],
            },
        ),
    ]
