# Generated by Django 5.2.13 on 2026-05-28 17:59

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baay', '0054_article_actualite'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlertePrix',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('produit_nom', models.CharField(db_index=True, max_length=100)),
                ('marche_nom', models.CharField(max_length=150)),
                ('region', models.CharField(blank=True, max_length=100)),
                ('variation_pct', models.FloatField(help_text='Variation en % (positif = hausse, négatif = baisse).')),
                ('prix_actuel', models.DecimalField(decimal_places=2, max_digits=12)),
                ('prix_reference', models.DecimalField(decimal_places=2, max_digits=12)),
                ('unite', models.CharField(default='FCFA/kg', max_length=30)),
                ('periode_jours', models.IntegerField(default=7, help_text='Fenêtre de comparaison : 7 ou 30 jours.')),
                ('niveau', models.CharField(choices=[('info', 'ℹ️ Informatif'), ('warning', '⚠️ Variation importante'), ('critique', '🔴 Variation critique')], db_index=True, default='warning', max_length=20)),
                ('date_detection', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('vue', models.BooleanField(db_index=True, default=False, help_text="True = l'alerte a été vue dans le dashboard.")),
            ],
            options={
                'verbose_name': 'Alerte prix',
                'verbose_name_plural': 'Alertes prix',
                'ordering': ['-date_detection'],
                'indexes': [models.Index(fields=['niveau', '-date_detection'], name='baay_alerte_niveau_58aa14_idx'), models.Index(fields=['vue', '-date_detection'], name='baay_alerte_vue_d2f65c_idx'), models.Index(fields=['produit_nom', '-date_detection'], name='baay_alerte_produit_ddf98d_idx')],
                'unique_together': {('produit_nom', 'marche_nom', 'periode_jours', 'date_detection')},
            },
        ),
        migrations.CreateModel(
            name='PrixMarche',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('produit_nom', models.CharField(db_index=True, help_text='Nom normalisé du produit (mil, sorgho, maïs, arachide…).', max_length=100)),
                ('marche_nom', models.CharField(db_index=True, help_text='Nom du marché (Kaolack, Dakar-Sandaga, Ziguinchor…).', max_length=150)),
                ('region', models.CharField(blank=True, db_index=True, max_length=100)),
                ('pays', models.CharField(default='Sénégal', max_length=50)),
                ('prix_unitaire', models.DecimalField(decimal_places=2, help_text='Prix en FCFA par unité (généralement kg ou sac 50 kg).', max_digits=12)),
                ('unite', models.CharField(default='FCFA/kg', help_text='Unité du prix : FCFA/kg, FCFA/sac50kg, etc.', max_length=30)),
                ('qualite', models.CharField(blank=True, help_text='Qualité ou type : local, importé, gros, détail…', max_length=50)),
                ('source', models.CharField(choices=[('fao_fpma', 'FAO FPMA (Global Food Prices)'), ('oma', 'OMA Sénégal'), ('resimao', "RESIMAO (Afrique de l'Ouest)"), ('autre', 'Autre source')], db_index=True, default='autre', max_length=20)),
                ('source_id', models.CharField(blank=True, help_text="Identifiant externe utilisé pour l'idempotence (ex: FAO FPMA point ID).", max_length=200)),
                ('date_relevee', models.DateField(db_index=True, help_text="Date d'observation du prix.")),
                ('date_collecte', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Prix marché',
                'verbose_name_plural': 'Prix marchés',
                'ordering': ['-date_relevee', 'produit_nom'],
                'indexes': [models.Index(fields=['produit_nom', '-date_relevee'], name='baay_prixma_produit_a9ff1b_idx'), models.Index(fields=['marche_nom', '-date_relevee'], name='baay_prixma_marche__90b96f_idx'), models.Index(fields=['region', '-date_relevee'], name='baay_prixma_region_e92938_idx'), models.Index(fields=['source', '-date_relevee'], name='baay_prixma_source_30b414_idx')],
                'unique_together': {('produit_nom', 'marche_nom', 'date_relevee', 'source')},
            },
        ),
    ]
