# Generated by Django 5.2.13 on 2026-06-03 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baay', '0055_prix_marche_alerte_prix'),
    ]

    operations = [
        migrations.AddField(
            model_name='previsionfeatures',
            name='synthetique',
            field=models.BooleanField(db_index=True, default=False, help_text="True si l'observation provient de données générées (seed). EXCLUE de l'entraînement ML pour ne pas réapprendre le générateur."),
        ),
    ]
