# Generated by Django 5.2.13 on 2026-06-14 12:18

import django.db.models.deletion
import uuid
from django.db import migrations, models


def backfill_account_type(apps, schema_editor):
    """Comptes existants = fermiers : ils gardent le parcours actuel et ne voient
    pas l'écran de choix de profil."""
    Profile = apps.get_model('baay', 'Profile')
    Profile.objects.filter(account_type__isnull=True).update(account_type='fermier')


class Migration(migrations.Migration):

    dependencies = [
        ('baay', '0057_backfill_synthetique_seed'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='account_type',
            field=models.CharField(blank=True, choices=[('fermier', 'Fermier indépendant'), ('cooperative', 'Coopérative'), ('technicien', 'Technicien agricole'), ('ouvrier', 'Ouvrier agricole')], help_text="Type de compte choisi à l'inscription ; pilote le parcours d'onboarding.", max_length=20, null=True),
        ),
        migrations.RunPython(backfill_account_type, migrations.RunPython.noop),
        migrations.CreateModel(
            name='Cooperative',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('code_acces', models.CharField(blank=True, max_length=12, unique=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('localite', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='baay.localite')),
                ('pays', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='baay.pays')),
                ('region', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='baay.region')),
            ],
            options={
                'ordering': ['nom'],
            },
        ),
        migrations.AddField(
            model_name='ferme',
            name='cooperative',
            field=models.ForeignKey(blank=True, help_text='Coopérative à laquelle la ferme est affiliée (le propriétaire reste propriétaire).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fermes', to='baay.cooperative'),
        ),
        migrations.CreateModel(
            name='MembreCooperative',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('role', models.CharField(choices=[('admin', 'Admin / Président'), ('gestionnaire', 'Gestionnaire'), ('technicien', 'Technicien coop'), ('consultant', 'Consultant'), ('fermier_affilie', 'Fermier affilié')], default='fermier_affilie', max_length=20)),
                ('peut_gerer_membres', models.BooleanField(default=False)),
                ('statut', models.CharField(choices=[('actif', 'Actif'), ('suspendu', 'Suspendu')], default='actif', max_length=12)),
                ('date_adhesion', models.DateTimeField(auto_now_add=True)),
                ('date_expiration', models.DateTimeField(blank=True, null=True)),
                ('cooperative', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='membres', to='baay.cooperative')),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cooperatives_membre', to='baay.profile')),
            ],
            options={
                'indexes': [models.Index(fields=['utilisateur', 'statut'], name='baay_coopmembre_user_idx')],
                'unique_together': {('cooperative', 'utilisateur')},
            },
        ),
    ]
