"""
Django settings for Andd_Baayi project.

Generated by 'django-admin startproject' using Django 5.1.4.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""
import os
from pathlib import Path
from dotenv import load_dotenv
from urllib.parse import urlsplit, urlunsplit, parse_qsl, urlencode
from datetime import timedelta

from django.templatetags.static import static
from django.urls import reverse_lazy

# Charger les variables du fichier .env
load_dotenv()

GOOGLE_API_KEY = os.getenv("GOOGLE_API_KEY")
OPENWEATHER_API_KEY = os.getenv("OPENWEATHER_API_KEY", "").strip()
WEATHER_CACHE_TTL_MINUTES = int(os.getenv("WEATHER_CACHE_TTL_MINUTES", "30"))

# ── Cloudinary (médias : CLOUDINARY_URL requis pour le stockage distant) ──
CLOUDINARY_URL = os.getenv("CLOUDINARY_URL", "").strip()
CLOUDINARY_MEDIA_PREFIX = (
    os.getenv("CLOUDINARY_MEDIA_PREFIX", "").strip()
    or ("prod" if os.getenv("ENV", "").lower() == "production" else "dev")
)

_srcset_w = os.getenv("CLOUDINARY_SRCSET_WIDTHS", "320,480,640,960").strip()
CLOUDINARY_SRCSET_WIDTHS = tuple(
    int(x.strip()) for x in _srcset_w.split(",") if x.strip().isdigit()
)
if not CLOUDINARY_SRCSET_WIDTHS:
    CLOUDINARY_SRCSET_WIDTHS = (320, 480, 640, 960)


def _parse_cloudinary_url(url: str) -> dict:
    """cloudinary://API_KEY:API_SECRET@CLOUD_NAME"""
    from urllib.parse import unquote, urlparse

    cleaned = url.replace("cloudinary://", "https://", 1)
    parsed = urlparse(cleaned)
    key = unquote(parsed.username or "")
    secret = unquote(parsed.password or "")
    cloud = (parsed.hostname or "").split("/")[0]
    if not all([key, secret, cloud]):
        raise ValueError("CLOUDINARY_URL invalide (cloudinary://API_KEY:API_SECRET@CLOUD_NAME)")
    return {"API_KEY": key, "API_SECRET": secret, "CLOUD_NAME": cloud}


CLOUDINARY_ACTIVE = bool(CLOUDINARY_URL)
_CLOUDINARY_PARSED = None
if CLOUDINARY_ACTIVE:
    try:
        _CLOUDINARY_PARSED = _parse_cloudinary_url(CLOUDINARY_URL)
    except ValueError as e:
        raise ValueError(f"Configuration Cloudinary : {e}") from e

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

IS_VERCEL = os.getenv("VERCEL") == "1"
VERCEL_URL = os.getenv("VERCEL_URL", "").strip()  # e.g. "my-app.vercel.app" (no scheme)

# Trusted Web Activity / Digital Asset Links (Play Store)
# https://developer.android.com/training/app-links/add-applinks#web-assoc
# Renseignez ANDROID_ASSETLINKS_SHA256 une fois la clé de signature obtenue (empreintes séparées par des virgules).
ANDROID_PACKAGE_NAME = os.getenv("ANDROID_PACKAGE_NAME", "").strip()
ANDROID_ASSETLINKS_SHA256 = os.getenv("ANDROID_ASSETLINKS_SHA256", "").strip()

STATIC_URL = '/static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
_secret_key = os.getenv('DJANGO_SECRET_KEY')
if not _secret_key:
    raise ValueError(
        "DJANGO_SECRET_KEY environment variable is required. "
        "Generate one with: python -c \"from django.core.management.utils import get_random_secret_key; print(get_random_secret_key())\""
    )
SECRET_KEY = _secret_key

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv('DEBUG', 'False').lower() in ('true', '1', 'yes')
_allow_debug_in_prod = os.getenv("ALLOW_DEBUG_IN_PROD", "").strip().lower() in ("1", "true", "yes")
if IS_VERCEL and DEBUG and not _allow_debug_in_prod:
    DEBUG = False

_explicit_production = (
    IS_VERCEL
    or os.getenv("ENV", "").strip().lower() == "production"
    or os.getenv("DJANGO_ENVIRONMENT", "").strip().lower() == "production"
    or os.getenv("DJANGO_DEPLOY_ENV", "").strip().lower() == "production"
)

if _explicit_production and not _allow_debug_in_prod:
    # Django's deploy checks flag weak/insecure keys. Enforce strength in explicit production.
    if SECRET_KEY.startswith("django-insecure-") or len(SECRET_KEY) < 50:
        raise ValueError("DJANGO_SECRET_KEY must be a strong random value (>=50 chars) in production.")

ALLOWED_HOSTS = [
    h.strip()
    for h in os.getenv(
        'ALLOWED_HOSTS',
        'andd-baay.onrender.com,andd-baay.vercel.app,.vercel.app,localhost,127.0.0.1',
    ).split(',')
    if h.strip()
]
if IS_VERCEL and VERCEL_URL:
    # Ensure the current deployment host is always accepted.
    if VERCEL_URL not in ALLOWED_HOSTS:
        ALLOWED_HOSTS.append(VERCEL_URL)

# Daphne est requis pour runserver ASGI / WebSockets en local ; absent sur Vercel (WSGI uniquement).
INSTALLED_APPS = [
    *([] if IS_VERCEL else ['daphne']),
    'unfold',
    'unfold.contrib.filters',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.humanize',
    'cloudinary_storage',
    'cloudinary',
    'baay.apps.BaayConfig',
    'rest_framework',
    'rest_framework.authtoken',
    'corsheaders',             # Pour django-cors-headers
    'rest_framework_simplejwt',
    'django.contrib.sites',
    'allauth',
    'allauth.account',
    'allauth.socialaccount',
    'allauth.socialaccount.providers.google',
    'channels',
    'axes',
]

# django-debug-toolbar : audit empirique des requêtes / temps / cache en dev.
# Strictement hors Vercel (jamais en prod) ; conditionné par DEBUG + import disponible.
DEBUG_TOOLBAR_ENABLED = DEBUG and not IS_VERCEL
if DEBUG_TOOLBAR_ENABLED:
    try:
        import debug_toolbar  # noqa: F401
        INSTALLED_APPS.append('debug_toolbar')
    except ImportError:
        DEBUG_TOOLBAR_ENABLED = False

SITE_ID = 1

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'baay.middleware.csp.ContentSecurityPolicyMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.locale.LocaleMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'axes.middleware.AxesMiddleware',
    # After AuthenticationMiddleware: needs request.user for HTMX fragment cache keys
    'baay.middleware.htmx_cache.HtmxCacheMiddleware',
    'baay.middleware.current_request.CurrentRequestMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'allauth.account.middleware.AccountMiddleware',
    # Response header so /static/js/sw.js can use navigator.serviceWorker.register(..., { scope: '/' })
    'baay.middleware.service_worker_scope.ServiceWorkerAllowedMiddleware',
]

# debug-toolbar middleware : doit être inséré aussi tôt que possible mais après
# les middlewares qui modifient la réponse (whitenoise, gzip…). Voir docs.
if DEBUG_TOOLBAR_ENABLED:
    MIDDLEWARE.insert(
        MIDDLEWARE.index('django.middleware.common.CommonMiddleware'),
        'debug_toolbar.middleware.DebugToolbarMiddleware',
    )
    INTERNAL_IPS = ['127.0.0.1', 'localhost']
    DEBUG_TOOLBAR_CONFIG = {
        # Le toolbar ne s'affiche pas sur les requêtes HTMX (sinon il pollue les fragments).
        # On utilise plutôt le panneau "History" pour analyser les requêtes asynchrones.
        'SHOW_TOOLBAR_CALLBACK': 'Andd_Baayi.settings.show_toolbar_callback',
    }


def show_toolbar_callback(request):
    """N'affiche le toolbar que pour les requêtes HTML interactives (pas HTMX/AJAX)."""
    if not DEBUG_TOOLBAR_ENABLED:
        return False
    if request.headers.get('HX-Request') == 'true':
        return False
    if request.headers.get('X-Requested-With') == 'XMLHttpRequest':
        return False
    return request.META.get('REMOTE_ADDR') in (INTERNAL_IPS if 'INTERNAL_IPS' in globals() else ['127.0.0.1'])

# CSP (Content Security Policy)
# Report-only can be enabled in env without breaking the UI: CSP_REPORT_ONLY=True
CSP_REPORT_ONLY = os.getenv("CSP_REPORT_ONLY", "False").lower() in ("1", "true", "yes")

# ── HTMX Fragment Cache (Phase 2) ───────────────────────────────────────────
HTMX_CACHE_TTL = 60  # secondes — durée de cache des fragments HTMX
HTMX_CACHE_EXEMPT_PATHS = [
    "/dashboard/partial/messages/",  # messages : non mis en cache (contenu personnel temps-réel)
]

# On Vercel, we typically do not run `collectstatic` during build for Python serverless,
# and static assets are served via `@vercel/static` routes. Avoid manifest strictness.
if IS_VERCEL:
    STATICFILES_STORAGE = 'django.contrib.staticfiles.storage.StaticFilesStorage'
    WHITENOISE_MANIFEST_STRICT = False
else:
    STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'

CORS_ALLOWED_ORIGINS = [
    "http://localhost:8501"
]

CSRF_TRUSTED_ORIGINS = [
    "https://andd-baay.onrender.com",
    "https://andd-baay.vercel.app",
    "https://*.vercel.app",
]
if IS_VERCEL and VERCEL_URL:
    origin = f"https://{VERCEL_URL}"
    if origin not in CSRF_TRUSTED_ORIGINS:
        CSRF_TRUSTED_ORIGINS.append(origin)

_extra_csrf = os.getenv("CSRF_TRUSTED_ORIGINS_EXTRA", "").strip()
if _extra_csrf:
    for _o in _extra_csrf.split(","):
        _o = _o.strip()
        if _o and _o not in CSRF_TRUSTED_ORIGINS:
            CSRF_TRUSTED_ORIGINS.append(_o)

# Vercel forwards HTTPS via X-Forwarded-Proto
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')

# Cookies-only over HTTPS in production (avoids session issues behind Vercel TLS)
if IS_VERCEL or not DEBUG:
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True

# Security hardening for production-like environments (Vercel + non-DEBUG)
_prod_like = IS_VERCEL or (not DEBUG)
if _prod_like:
    SECURE_SSL_REDIRECT = True
    SECURE_REFERRER_POLICY = "strict-origin-when-cross-origin"
    SECURE_CONTENT_TYPE_NOSNIFF = True
    X_FRAME_OPTIONS = os.getenv("X_FRAME_OPTIONS", "DENY")

    # HSTS: start small, raise progressively via env.
    SECURE_HSTS_SECONDS = int(os.getenv("SECURE_HSTS_SECONDS", "86400"))
    SECURE_HSTS_INCLUDE_SUBDOMAINS = os.getenv("SECURE_HSTS_INCLUDE_SUBDOMAINS", "False").lower() in ("1", "true", "yes")
    SECURE_HSTS_PRELOAD = os.getenv("SECURE_HSTS_PRELOAD", "False").lower() in ("1", "true", "yes")

ROOT_URLCONF = 'Andd_Baayi.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'baay.context_processors.exploitation_section',
                'baay.context_processors.finance_section',
                'baay.context_processors.auth_backgrounds',
            ],
        },
    },
]

WSGI_APPLICATION = 'Andd_Baayi.wsgi.application'
ASGI_APPLICATION = 'Andd_Baayi.asgi.application'

# Channels (WebSockets) — in-memory en dev ; Redis si REDIS_URL (hors Vercel).
# Sur Vercel : pas de package channels_redis ; couche mémoire uniquement.
_redis_url = os.getenv('REDIS_URL', '').strip()
if IS_VERCEL:
    CHANNEL_LAYERS = {
        'default': {
            'BACKEND': 'channels.layers.InMemoryChannelLayer',
        }
    }
else:
    CHANNEL_LAYERS = {
        'default': {
            'BACKEND': 'channels.layers.InMemoryChannelLayer',
        }
    }
    if _redis_url:
        CHANNEL_LAYERS = {
            'default': {
                'BACKEND': 'channels_redis.core.RedisChannelLayer',
                'CONFIG': {
                    'hosts': [_redis_url],
                },
            }
        }

# Celery — broker explicite ou REDIS_URL ; en DEBUG sans les deux : pas de Redis requis (eager + memory).
_celery_broker_env = os.getenv('CELERY_BROKER_URL', '').strip()
_redis_env = _redis_url

if _celery_broker_env:
    CELERY_BROKER_URL = _celery_broker_env
elif _redis_env:
    CELERY_BROKER_URL = _redis_env
elif DEBUG:
    CELERY_BROKER_URL = 'memory://'
else:
    CELERY_BROKER_URL = 'redis://localhost:6379/0'

CELERY_RESULT_BACKEND_ENV = os.getenv('CELERY_RESULT_BACKEND', '').strip()
if CELERY_RESULT_BACKEND_ENV:
    CELERY_RESULT_BACKEND = CELERY_RESULT_BACKEND_ENV
elif str(CELERY_BROKER_URL).startswith('memory'):
    # Celery attend une URL de backend (`memory://` seul est résolu comme module Python inexistant).
    CELERY_RESULT_BACKEND = 'cache+memory://'
else:
    CELERY_RESULT_BACKEND = CELERY_BROKER_URL

_eager_env = os.getenv('CELERY_TASK_ALWAYS_EAGER', '').strip().lower()
if _eager_env in ('1', 'true', 'yes'):
    CELERY_TASK_ALWAYS_EAGER = True
elif _eager_env in ('0', 'false', 'no'):
    CELERY_TASK_ALWAYS_EAGER = False
else:
    CELERY_TASK_ALWAYS_EAGER = DEBUG and not (_celery_broker_env or _redis_env)

CELERY_TASK_EAGER_PROPAGATES = True
CELERY_TASK_TIME_LIMIT = int(os.getenv('CELERY_TASK_TIME_LIMIT', '900'))
CELERY_TASK_SOFT_TIME_LIMIT = int(os.getenv('CELERY_TASK_SOFT_TIME_LIMIT', '600'))

# Pas de broker Redis/worker sur Vercel : tâches exécutées dans le processus Lambda.
if IS_VERCEL:
    CELERY_BROKER_URL = 'memory://'
    CELERY_RESULT_BACKEND = 'cache+memory://'
    CELERY_TASK_ALWAYS_EAGER = True

# Django-Axes — brute force protection
AXES_ENABLED = os.getenv('AXES_ENABLED', 'True').lower() in ('1', 'true', 'yes')
AXES_FAILURE_LIMIT = int(os.getenv('AXES_FAILURE_LIMIT', '5'))
AXES_COOLOFF_TIME = timedelta(minutes=int(os.getenv('AXES_COOLOFF_MINUTES', '15')))
# Critères composés pour le suivi des tentatives (liste requise par django-axes 6+ ;
# un groupe interne = AND sur ces champs pour une même entrée de suivi).
AXES_LOCKOUT_PARAMETERS = [["username", "ip_address", "user_agent"]]
AXES_ONLY_ADMIN_SITE = os.getenv('AXES_ONLY_ADMIN_SITE', 'False').lower() in ('1', 'true', 'yes')


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

DATABASE_URL = os.getenv("DATABASE_URL", "").strip()

if DATABASE_URL:
    import dj_database_url

    # Supabase/Vercel env vars sometimes include non-libpq query params like `supa` / `pgbouncer`.
    # psycopg will error on unknown connection options, so we strip them defensively.
    try:
        parts = urlsplit(DATABASE_URL)
        query = [(k, v) for (k, v) in parse_qsl(parts.query, keep_blank_values=True) if k not in {"supa", "pgbouncer"}]
        # Switch to Transaction pooler (port 6543) to fix MaxClientsInSessionMode on Supabase.
        # Session mode (port 5432) is capped; Transaction mode handles serverless much better.
        netloc = parts.netloc.replace(":5432", ":6543")
        DATABASE_URL = urlunsplit((parts.scheme, netloc, parts.path, urlencode(query), parts.fragment))
    except Exception:
        # If parsing fails, fall back to the raw value and let Django surface the error.
        pass

    DATABASES = {
        # conn_max_age=0: no persistent connections between serverless Vercel invocations.
        "default": dj_database_url.parse(DATABASE_URL, conn_max_age=0, ssl_require=True),
    }
elif os.getenv('ENV') == 'production':
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.postgresql',
            'NAME': os.getenv('DB_NAME'),
            'USER': os.getenv('DB_USER'),
            'PASSWORD': os.getenv('DB_PASSWORD'),
            'HOST': os.getenv('DB_HOST'),
            'PORT': os.getenv('DB_PORT', '5432'),
        }
    }
else:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
        }
    }

# Les curseurs nommés côté serveur (QuerySet.iterator chunké, etc.) sont incompatibles avec
# PgBouncer en pooling « transaction » (ex. Supabase :6543) et peuvent lever
# InvalidCursorName (« cursor "_django_curs_…" does not exist »). On les désactive pour PostgreSQL.
for _alias, _cfg in DATABASES.items():
    if _cfg.get("ENGINE") == "django.db.backends.postgresql":
        # `dj_database_url.parse()` may set this explicitly to False; override to True
        # to avoid InvalidCursorName with PgBouncer transaction pooling (Supabase :6543).
        _cfg["DISABLE_SERVER_SIDE_CURSORS"] = True

# Cache Django — backend locmem par défaut (Axes, etc.)
CACHES = {
    'default': {
        'BACKEND': 'django.core.cache.backends.locmem.LocMemCache',
        'LOCATION': 'anddbaay-locmem-default',
    }
}

# Password validation
AUTH_PASSWORD_VALIDATORS = [
    {'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator'},
    {'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator'},
    {'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator'},
    {'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator'},
]

# Internationalization
LANGUAGE_CODE = 'fr'
TIME_ZONE = 'UTC'
USE_I18N = True
USE_TZ = True

# Default primary key field type
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Authentication backends for allauth
AUTHENTICATION_BACKENDS = [
    'axes.backends.AxesStandaloneBackend',
    'django.contrib.auth.backends.ModelBackend',
    'allauth.account.auth_backends.AuthenticationBackend',
]

# OAuth / email links must use https in production so redirect URIs match Google Console
if IS_VERCEL or not DEBUG:
    ACCOUNT_DEFAULT_HTTP_PROTOCOL = "https"

# ============================================================
# django-allauth / Social Auth
# ============================================================

# Account settings
ACCOUNT_EMAIL_VERIFICATION = 'mandatory'
ACCOUNT_LOGIN_METHODS = {'email', 'username'}
# email* / username* / password* = champs obligatoires (remplace ACCOUNT_EMAIL_REQUIRED déprécié)
ACCOUNT_SIGNUP_FIELDS = ['email*', 'username*', 'password1*', 'password2*']
ACCOUNT_UNIQUE_EMAIL = True

# Skip email verification for social logins (Google already verified the email)
SOCIALACCOUNT_EMAIL_VERIFICATION = 'none'
SOCIALACCOUNT_EMAIL_REQUIRED = False

# Social account settings
# GOOGLE_OAUTH_PROMPT :
#   - vide (défaut) : comportement Google standard, moins d’écrans « verify it's you » pour certains comptes.
#   - select_account : force le choix du compte (utile si plusieurs Gmail sur le même navigateur).
_google_oauth_prompt = os.getenv("GOOGLE_OAUTH_PROMPT", "").strip()
_google_auth_params = {"access_type": "online"}
if _google_oauth_prompt:
    _google_auth_params["prompt"] = _google_oauth_prompt

SOCIALACCOUNT_PROVIDERS = {
    "google": {
        "SCOPE": ["profile", "email"],
        "AUTH_PARAMS": _google_auth_params,
        "OAUTH_PKCE_ENABLED": True,
    }
}

# Auto-create account if Google email is new
SOCIALACCOUNT_AUTO_SIGNUP = True
# Skip confirmation page after Google OAuth
SOCIALACCOUNT_LOGIN_ON_GET = True
SOCIALACCOUNT_QUERY_EMAIL = True

# Redirects
LOGIN_REDIRECT_URL = '/dashboard/'
ACCOUNT_LOGOUT_REDIRECT_URL = '/'

# Force session save on every request — required for serverless (Vercel)
# where the OAuth callback may hit a different instance than the redirect.
SESSION_SAVE_EVERY_REQUEST = True

# Custom adapter to populate names from Google profile
SOCIALACCOUNT_ADAPTER = 'baay.adapters.CustomSocialAccountAdapter'

# REST Framework configuration
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework_simplejwt.authentication.JWTAuthentication',
        'rest_framework.authentication.SessionAuthentication',
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',
    ],
}

# Email settings
# - Si EMAIL_HOST_USER et EMAIL_HOST_PASSWORD sont fournis, on utilise SMTP.
# - Sinon, fallback automatique sur le backend console (les emails s'affichent
#   dans les logs du serveur) : pratique en dev pour ne pas casser les flux.
EMAIL_HOST = os.getenv('EMAIL_HOST', 'smtp.gmail.com')
EMAIL_PORT = int(os.getenv('EMAIL_PORT', '587'))
EMAIL_HOST_USER = os.getenv('EMAIL_HOST_USER', '')
EMAIL_HOST_PASSWORD = os.getenv('EMAIL_HOST_PASSWORD', '')
EMAIL_USE_TLS = os.getenv('EMAIL_USE_TLS', 'True').lower() in ('1', 'true', 'yes')
EMAIL_USE_SSL = os.getenv('EMAIL_USE_SSL', 'False').lower() in ('1', 'true', 'yes')
EMAIL_TIMEOUT = int(os.getenv('EMAIL_TIMEOUT', '15'))
DEFAULT_FROM_EMAIL = os.getenv('DEFAULT_FROM_EMAIL', EMAIL_HOST_USER or 'no-reply@anddbaay.local')
SERVER_EMAIL = DEFAULT_FROM_EMAIL

if os.getenv('EMAIL_BACKEND'):
    EMAIL_BACKEND = os.getenv('EMAIL_BACKEND')
elif EMAIL_HOST_USER and EMAIL_HOST_PASSWORD:
    EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
else:
    # Pas de credentials SMTP → on évite les erreurs en envoyant vers la console
    EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'

MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'baay/static/media')

if CLOUDINARY_ACTIVE and _CLOUDINARY_PARSED:
    CLOUDINARY_STORAGE = {
        'CLOUD_NAME': _CLOUDINARY_PARSED['CLOUD_NAME'],
        'API_KEY': _CLOUDINARY_PARSED['API_KEY'],
        'API_SECRET': _CLOUDINARY_PARSED['API_SECRET'],
    }
    DEFAULT_FILE_STORAGE = 'cloudinary_storage.storage.MediaCloudinaryStorage'
else:
    DEFAULT_FILE_STORAGE = 'django.core.files.storage.FileSystemStorage'

# ── Auth Background Images (Cloudinary URLs) ────────────────────────────────
# These are set automatically by the upload_auth_images management command.
# Fallback to static files if not configured.
LOGIN_BG_CLOUDINARY_URL = os.getenv("LOGIN_BG_CLOUDINARY_URL", "").strip()
SIGNUP_BG_CLOUDINARY_URL = os.getenv("SIGNUP_BG_CLOUDINARY_URL", "").strip()


# Environnement d'exécution affiché dans l'admin Unfold (badge + préfixe title).
# Ex. .env : DJANGO_ENVIRONMENT=staging  |  production  |  development
DJANGO_DEPLOY_ENV = (
    os.getenv("DJANGO_ENVIRONMENT", "").strip().lower()
    or os.getenv("DJANGO_DEPLOY_ENV", "").strip().lower()
    or ("development" if DEBUG else "production")
)
DJANGO_DEPLOY_LABELS = {
    "production": ("Production", "danger"),
    "staging": ("Pré-production", "warning"),
    "preview": ("Aperçu", "warning"),
    "development": ("Développement", "primary"),
    "local": ("Local", "info"),
    "default": ("Environnement", "primary"),
}
DJANGO_DEPLOY_TITLE_PREFIX_MAP = {
    "staging": "[Préprod] ",
    "preview": "[Aperçu] ",
    "development": "[Dev] ",
    "local": "[Local] ",
}
DJANGO_DEPLOY_TITLE_PREFIX = DJANGO_DEPLOY_TITLE_PREFIX_MAP.get(DJANGO_DEPLOY_ENV, "")


# Logging configuration
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '{levelname} {asctime} {module} {process:d} {thread:d} {message}',
            'style': '{',
        },
        'simple': {
            'format': '{levelname} {message}',
            'style': '{',
        },
    },
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
            'formatter': 'simple',
        },
    },
    'root': {
        'handlers': ['console'],
        'level': 'WARNING',
    },
    'loggers': {
        'baay': {
            'handlers': ['console'],
            'level': os.getenv('LOG_LEVEL', 'INFO'),
            'propagate': False,
        },
    },
}


# =============================================================================
# Django Unfold — thème admin (mobile-first, palette Andd Baay)
# =============================================================================

UNFOLD = {
    "SITE_TITLE": "Andd Baay — Administration",
    "SITE_HEADER": "Gestion agricole collaborative",
    "SITE_SUBHEADER": "Sénégal — console d'administration",
    "SITE_URL": reverse_lazy("dashboard"),
    "SITE_ICON": lambda request: static("admin/anddbaay-mark.svg"),
    "SITE_LOGO": lambda request: {
        "light": static("admin/anddbaay-mark.svg"),
        "dark": static("admin/anddbaay-mark.svg"),
    },
    "SITE_FAVICONS": [
        {
            "rel": "icon",
            "sizes": "32x32",
            "type": "image/svg+xml",
            "href": lambda request: static("admin/anddbaay-mark.svg"),
        },
        {
            "rel": "icon",
            "sizes": "192x192",
            "type": "image/png",
            "href": lambda request: static("icons/icon-192x192.png"),
        },
    ],
    "SHOW_HISTORY": True,
    "SHOW_VIEW_ON_SITE": True,
    "SHOW_BACK_BUTTON": True,
    "ENVIRONMENT_TITLE_PREFIX": "baay.unfold_callbacks.unfold_environment_title_prefix",
    "ENVIRONMENT": "baay.unfold_callbacks.unfold_environment_badge",
    # Align with app design tokens (--radius-card ≈ 22px)
    "BORDER_RADIUS": "22px",
    "COLORS": {
        "primary": {
            "50": "#ecf9f4",
            "100": "#d4f2e8",
            "200": "#a8e5d1",
            "300": "#5DCAA5",
            "400": "#3cb08c",
            "500": "#1D9E75",
            "600": "#178f6a",
            "700": "#0d6b52",
            "800": "#085041",
            "900": "#063830",
            "950": "#04221c",
        },
    },
    "DASHBOARD_CALLBACK": "baay.admin_dashboard.dashboard_callback",
    # Personnalise la page d’accueil admin (`admin/index.html`) : KPIs filtrés,
    # ApexCharts et couches Propriétaire / Manager / Technicien (baay.dashboard_services).
    # Navigation : Unfold masque la sidebar sur mobile (< xl) et l’affiche en overlay
    # via `sidebarMobileOpen` (menu hamburger). Pas de clé supplémentaire requise.
    "SIDEBAR": {
        "show_search": True,
        "show_all_applications": True,
        "command_search": True,
        "navigation": [
            {
                "title": "Gestion financière",
                "separator": True,
                "collapsible": True,
                "items": [
                    {
                        "title": "Investissements",
                        "icon": "payments",
                        "link": reverse_lazy("admin:baay_investissement_changelist"),
                    },
                    {
                        "title": "Projets",
                        "icon": "account_balance",
                        "link": reverse_lazy("admin:baay_projet_changelist"),
                    },
                    {
                        "title": "Produits agricoles (prix)",
                        "icon": "inventory_2",
                        "link": reverse_lazy("admin:baay_produitagricole_changelist"),
                    },
                ],
            },
        ],
    },
    "COMMAND": {
        "search_models": True,
        "show_history": False,
    },
}
