from django.core.management.base import BaseCommand
from django.core.exceptions import ValidationError
from baay.models import ProduitAgricole


class Command(BaseCommand):
    help = "Ajoute toutes les cultures d'Afrique de l'Ouest et les cultures émergentes dans la base de données."

    def handle(self, *args, **options):
        cultures = self._get_cultures_data()
        created = 0
        skipped = 0

        for data in cultures:
            nom = data.pop("nom")
            try:
                _, is_new = ProduitAgricole.objects.get_or_create(
                    nom=nom, defaults=data
                )
                if is_new:
                    created += 1
                    self.stdout.write(f"  + {nom}")
                else:
                    skipped += 1
            except (ValidationError, Exception) as e:
                skipped += 1
                self.stdout.write(self.style.WARNING(f"  ~ {nom} (ignoré : {e})"))

        self.stdout.write(
            self.style.SUCCESS(
                f"\nTerminé : {created} cultures créées, {skipped} déjà existantes."
            )
        )

    # ------------------------------------------------------------------
    #  DATA
    # ------------------------------------------------------------------
    def _get_cultures_data(self):
        return [
            # ============================================================
            #  CÉRÉALES
            # ============================================================
            {
                "nom": "Mil",
                "description": "Céréale principale du Sahel, très résistante à la sécheresse. Base de l'alimentation en zone sahélienne.",
                "saison": "Hivernage",
                "prix_par_kg": 250,
                "rendement_moyen": 1200,
                "rendement_potentiel_max": 2000,
                "besoin_eau_mm": 400,
                "cycle_culture_jours": 95,
                "duree_avant_recolte": 95,
                "periode_recolte": "Septembre - Novembre",
            },
            {
                "nom": "Sorgho",
                "description": "Céréale résistante à la chaleur, utilisée pour la bouillie, le couscous et la bière locale (dolo).",
                "saison": "Hivernage",
                "prix_par_kg": 220,
                "rendement_moyen": 1400,
                "rendement_potentiel_max": 2300,
                "besoin_eau_mm": 450,
                "cycle_culture_jours": 105,
                "duree_avant_recolte": 105,
                "periode_recolte": "Octobre - Décembre",
            },
            {
                "nom": "Riz",
                "description": "Cultivé en irrigué (fleuve Sénégal, Office du Niger) et pluvial (Casamance, Guinée). Aliment de base croissant.",
                "saison": "Contre-saison / Hivernage",
                "prix_par_kg": 350,
                "rendement_moyen": 4500,
                "rendement_potentiel_max": 6500,
                "besoin_eau_mm": 900,
                "cycle_culture_jours": 120,
                "duree_avant_recolte": 120,
                "periode_recolte": "Novembre - Janvier",
            },
            {
                "nom": "Maïs",
                "description": "Céréale à cycle court, cultivée en zone soudanienne et guinéenne. Usage alimentaire et fourrage.",
                "saison": "Hivernage",
                "prix_par_kg": 200,
                "rendement_moyen": 2500,
                "rendement_potentiel_max": 5000,
                "besoin_eau_mm": 550,
                "cycle_culture_jours": 100,
                "duree_avant_recolte": 100,
                "periode_recolte": "Août - Octobre",
            },
            {
                "nom": "Fonio",
                "description": "Céréale ancestrale très nutritive, sans gluten. Cultivée en Guinée, Mali et Sénégal. Renaissance en cours.",
                "saison": "Hivernage",
                "prix_par_kg": 600,
                "rendement_moyen": 800,
                "rendement_potentiel_max": 1500,
                "besoin_eau_mm": 400,
                "cycle_culture_jours": 80,
                "duree_avant_recolte": 80,
                "periode_recolte": "Août - Septembre",
            },
            {
                "nom": "Blé",
                "description": "Culture irriguée de contre-saison dans la vallée du fleuve Sénégal et l'Office du Niger.",
                "saison": "Contre-saison",
                "prix_par_kg": 300,
                "rendement_moyen": 3000,
                "rendement_potentiel_max": 5000,
                "besoin_eau_mm": 450,
                "cycle_culture_jours": 110,
                "duree_avant_recolte": 110,
                "periode_recolte": "Mars - Mai",
            },

            # ============================================================
            #  LÉGUMINEUSES
            # ============================================================
            {
                "nom": "Arachide",
                "description": "Culture de rente majeure au Sénégal et en Gambie. Huile, pâte, tourteau. Fixe l'azote dans le sol.",
                "saison": "Hivernage",
                "prix_par_kg": 500,
                "rendement_moyen": 1100,
                "rendement_potentiel_max": 1800,
                "besoin_eau_mm": 550,
                "cycle_culture_jours": 110,
                "duree_avant_recolte": 110,
                "periode_recolte": "Octobre - Novembre",
            },
            {
                "nom": "Niébé",
                "description": "Haricot à œil noir, très résistant à la sécheresse. Riche en protéines, se cultive en association avec le mil.",
                "saison": "Hivernage",
                "prix_par_kg": 400,
                "rendement_moyen": 800,
                "rendement_potentiel_max": 1500,
                "besoin_eau_mm": 350,
                "cycle_culture_jours": 75,
                "duree_avant_recolte": 75,
                "periode_recolte": "Septembre - Octobre",
            },
            {
                "nom": "Soja",
                "description": "Légumineuse oléagineuse à forte teneur en protéines. Cultivé au Nigéria, Bénin, Togo.",
                "saison": "Hivernage",
                "prix_par_kg": 450,
                "rendement_moyen": 1500,
                "rendement_potentiel_max": 2500,
                "besoin_eau_mm": 500,
                "cycle_culture_jours": 110,
                "duree_avant_recolte": 110,
                "periode_recolte": "Octobre - Novembre",
            },
            {
                "nom": "Haricot vert",
                "description": "Légumineuse maraîchère d'export. Culture de contre-saison au Sénégal, Burkina Faso.",
                "saison": "Contre-saison",
                "prix_par_kg": 600,
                "rendement_moyen": 6000,
                "rendement_potentiel_max": 12000,
                "besoin_eau_mm": 400,
                "cycle_culture_jours": 60,
                "duree_avant_recolte": 60,
                "periode_recolte": "Décembre - Mars",
            },
            {
                "nom": "Lentille",
                "description": "Légumineuse riche en protéines et fer. Culture émergente en zone sahélienne irriguée.",
                "saison": "Contre-saison",
                "prix_par_kg": 700,
                "rendement_moyen": 900,
                "rendement_potentiel_max": 1800,
                "besoin_eau_mm": 350,
                "cycle_culture_jours": 100,
                "duree_avant_recolte": 100,
                "periode_recolte": "Février - Avril",
            },
            {
                "nom": "Pois de terre (Voandzou)",
                "description": "Légumineuse souterraine traditionnelle, très nutritive. Résistante à la sécheresse.",
                "saison": "Hivernage",
                "prix_par_kg": 450,
                "rendement_moyen": 700,
                "rendement_potentiel_max": 1200,
                "besoin_eau_mm": 400,
                "cycle_culture_jours": 120,
                "duree_avant_recolte": 120,
                "periode_recolte": "Octobre - Novembre",
            },
            {
                "nom": "Pois chiche",
                "description": "Légumineuse émergente en Afrique de l'Ouest. Potentiel en zones semi-arides irriguées.",
                "saison": "Contre-saison",
                "prix_par_kg": 800,
                "rendement_moyen": 1000,
                "rendement_potentiel_max": 2000,
                "besoin_eau_mm": 350,
                "cycle_culture_jours": 100,
                "duree_avant_recolte": 100,
                "periode_recolte": "Février - Avril",
            },

            # ============================================================
            #  TUBERCULES & RACINES
            # ============================================================
            {
                "nom": "Manioc",
                "description": "Racine tubéreuse majeure en zone forestière. Attiéké, gari, tapioca. Très tolérant aux sols pauvres.",
                "saison": "Toute l'année",
                "prix_par_kg": 150,
                "rendement_moyen": 12000,
                "rendement_potentiel_max": 25000,
                "besoin_eau_mm": 1000,
                "cycle_culture_jours": 300,
                "duree_avant_recolte": 300,
                "periode_recolte": "Toute l'année (8-18 mois)",
            },
            {
                "nom": "Igname",
                "description": "Tubercule noble en Afrique de l'Ouest (Nigéria, Ghana, Bénin, Côte d'Ivoire). Pilé, frit, bouilli.",
                "saison": "Hivernage",
                "prix_par_kg": 350,
                "rendement_moyen": 15000,
                "rendement_potentiel_max": 30000,
                "besoin_eau_mm": 1200,
                "cycle_culture_jours": 250,
                "duree_avant_recolte": 250,
                "periode_recolte": "Août - Décembre",
            },
            {
                "nom": "Patate douce",
                "description": "Tubercule à chair orange riche en vitamine A. Cycle court, adaptée aux petites exploitations.",
                "saison": "Hivernage / Contre-saison",
                "prix_par_kg": 200,
                "rendement_moyen": 8000,
                "rendement_potentiel_max": 15000,
                "besoin_eau_mm": 600,
                "cycle_culture_jours": 120,
                "duree_avant_recolte": 120,
                "periode_recolte": "Octobre - Décembre",
            },
            {
                "nom": "Pomme de terre",
                "description": "Cultivée en contre-saison dans les zones fraîches et irriguées. Niayes (Sénégal), plateau de Jos (Nigéria).",
                "saison": "Contre-saison",
                "prix_par_kg": 400,
                "rendement_moyen": 15000,
                "rendement_potentiel_max": 30000,
                "besoin_eau_mm": 500,
                "cycle_culture_jours": 90,
                "duree_avant_recolte": 90,
                "periode_recolte": "Janvier - Mars",
            },
            {
                "nom": "Taro",
                "description": "Tubercule cultivé en zone humide et marécageuse. Base alimentaire en Guinée et zones forestières.",
                "saison": "Hivernage",
                "prix_par_kg": 300,
                "rendement_moyen": 7000,
                "rendement_potentiel_max": 12000,
                "besoin_eau_mm": 1500,
                "cycle_culture_jours": 240,
                "duree_avant_recolte": 240,
                "periode_recolte": "Novembre - Janvier",
            },

            # ============================================================
            #  MARAÎCHAGE (LÉGUMES)
            # ============================================================
            {
                "nom": "Tomate",
                "description": "Légume le plus cultivé en maraîchage. Variétés locales et hybrides. Niayes, périmètres irrigués.",
                "saison": "Contre-saison / Toute l'année",
                "prix_par_kg": 350,
                "rendement_moyen": 20000,
                "rendement_potentiel_max": 40000,
                "besoin_eau_mm": 600,
                "cycle_culture_jours": 90,
                "duree_avant_recolte": 90,
                "periode_recolte": "Décembre - Mai",
            },
            {
                "nom": "Oignon",
                "description": "Culture maraîchère majeure au Sénégal (Niayes), Niger, Burkina Faso. Forte valeur commerciale.",
                "saison": "Contre-saison",
                "prix_par_kg": 300,
                "rendement_moyen": 25000,
                "rendement_potentiel_max": 45000,
                "besoin_eau_mm": 500,
                "cycle_culture_jours": 120,
                "duree_avant_recolte": 120,
                "periode_recolte": "Mars - Mai",
            },
            {
                "nom": "Piment",
                "description": "Condiment essentiel de la cuisine ouest-africaine. Variétés locales très piquantes.",
                "saison": "Hivernage / Contre-saison",
                "prix_par_kg": 500,
                "rendement_moyen": 5000,
                "rendement_potentiel_max": 10000,
                "besoin_eau_mm": 600,
                "cycle_culture_jours": 120,
                "duree_avant_recolte": 120,
                "periode_recolte": "Octobre - Février",
            },
            {
                "nom": "Poivron",
                "description": "Légume fruit cultivé en maraîchage périurbain et d'export.",
                "saison": "Contre-saison",
                "prix_par_kg": 500,
                "rendement_moyen": 12000,
                "rendement_potentiel_max": 25000,
                "besoin_eau_mm": 600,
                "cycle_culture_jours": 100,
                "duree_avant_recolte": 100,
                "periode_recolte": "Décembre - Avril",
            },
            {
                "nom": "Gombo",
                "description": "Légume incontournable des sauces ouest-africaines. Facile à cultiver, tolérant à la chaleur.",
                "saison": "Hivernage / Toute l'année",
                "prix_par_kg": 350,
                "rendement_moyen": 6000,
                "rendement_potentiel_max": 12000,
                "besoin_eau_mm": 500,
                "cycle_culture_jours": 60,
                "duree_avant_recolte": 60,
                "periode_recolte": "Août - Novembre",
            },
            {
                "nom": "Aubergine africaine (Jaxatu)",
                "description": "Aubergine amère très populaire en Afrique de l'Ouest pour les sauces. Résistante et productive.",
                "saison": "Toute l'année",
                "prix_par_kg": 300,
                "rendement_moyen": 10000,
                "rendement_potentiel_max": 18000,
                "besoin_eau_mm": 550,
                "cycle_culture_jours": 85,
                "duree_avant_recolte": 85,
                "periode_recolte": "Toute l'année",
            },
            {
                "nom": "Aubergine",
                "description": "Aubergine classique (violette). Maraîchage intensif en zone péri-urbaine.",
                "saison": "Contre-saison",
                "prix_par_kg": 350,
                "rendement_moyen": 15000,
                "rendement_potentiel_max": 30000,
                "besoin_eau_mm": 550,
                "cycle_culture_jours": 90,
                "duree_avant_recolte": 90,
                "periode_recolte": "Décembre - Avril",
            },
            {
                "nom": "Chou",
                "description": "Légume feuille de contre-saison, cultivé dans les Niayes et zones irriguées.",
                "saison": "Contre-saison",
                "prix_par_kg": 250,
                "rendement_moyen": 20000,
                "rendement_potentiel_max": 40000,
                "besoin_eau_mm": 450,
                "cycle_culture_jours": 80,
                "duree_avant_recolte": 80,
                "periode_recolte": "Décembre - Mars",
            },
            {
                "nom": "Laitue",
                "description": "Salade très demandée en zone urbaine. Culture de contre-saison dans les Niayes.",
                "saison": "Contre-saison",
                "prix_par_kg": 350,
                "rendement_moyen": 15000,
                "rendement_potentiel_max": 25000,
                "besoin_eau_mm": 350,
                "cycle_culture_jours": 45,
                "duree_avant_recolte": 45,
                "periode_recolte": "Novembre - Mars",
            },
            {
                "nom": "Carotte",
                "description": "Légume racine de contre-saison. Culture croissante dans les zones maraîchères.",
                "saison": "Contre-saison",
                "prix_par_kg": 350,
                "rendement_moyen": 20000,
                "rendement_potentiel_max": 35000,
                "besoin_eau_mm": 500,
                "cycle_culture_jours": 90,
                "duree_avant_recolte": 90,
                "periode_recolte": "Janvier - Avril",
            },
            {
                "nom": "Concombre",
                "description": "Cucurbitacée de maraîchage, consommée crue ou en salade. Bonne rentabilité.",
                "saison": "Contre-saison / Toute l'année",
                "prix_par_kg": 300,
                "rendement_moyen": 18000,
                "rendement_potentiel_max": 30000,
                "besoin_eau_mm": 500,
                "cycle_culture_jours": 55,
                "duree_avant_recolte": 55,
                "periode_recolte": "Décembre - Mai",
            },
            {
                "nom": "Courgette",
                "description": "Cucurbitacée à cycle très court. Maraîchage périurbain et d'export.",
                "saison": "Contre-saison",
                "prix_par_kg": 350,
                "rendement_moyen": 15000,
                "rendement_potentiel_max": 25000,
                "besoin_eau_mm": 450,
                "cycle_culture_jours": 50,
                "duree_avant_recolte": 50,
                "periode_recolte": "Décembre - Mars",
            },
            {
                "nom": "Navet",
                "description": "Légume racine de contre-saison, cultivé dans les Niayes sénégalaises.",
                "saison": "Contre-saison",
                "prix_par_kg": 250,
                "rendement_moyen": 15000,
                "rendement_potentiel_max": 25000,
                "besoin_eau_mm": 400,
                "cycle_culture_jours": 60,
                "duree_avant_recolte": 60,
                "periode_recolte": "Décembre - Mars",
            },
            {
                "nom": "Betterave",
                "description": "Légume racine riche en fer. Culture émergente en maraîchage ouest-africain.",
                "saison": "Contre-saison",
                "prix_par_kg": 350,
                "rendement_moyen": 18000,
                "rendement_potentiel_max": 30000,
                "besoin_eau_mm": 450,
                "cycle_culture_jours": 70,
                "duree_avant_recolte": 70,
                "periode_recolte": "Janvier - Avril",
            },
            {
                "nom": "Ail",
                "description": "Condiment et plante médicinale. Cultivé dans les zones fraîches (Niayes, plateau central).",
                "saison": "Contre-saison",
                "prix_par_kg": 1500,
                "rendement_moyen": 5000,
                "rendement_potentiel_max": 10000,
                "besoin_eau_mm": 400,
                "cycle_culture_jours": 150,
                "duree_avant_recolte": 150,
                "periode_recolte": "Mars - Mai",
            },
            {
                "nom": "Échalote",
                "description": "Condiment essentiel de la cuisine malienne et burkinabè. Très bonne valeur marchande.",
                "saison": "Contre-saison",
                "prix_par_kg": 500,
                "rendement_moyen": 15000,
                "rendement_potentiel_max": 25000,
                "besoin_eau_mm": 450,
                "cycle_culture_jours": 90,
                "duree_avant_recolte": 90,
                "periode_recolte": "Février - Avril",
            },
            {
                "nom": "Épinard africain (Amarante)",
                "description": "Légume feuille très nutritif, riche en fer et calcium. Pousse rapidement en zone tropicale.",
                "saison": "Toute l'année",
                "prix_par_kg": 250,
                "rendement_moyen": 8000,
                "rendement_potentiel_max": 15000,
                "besoin_eau_mm": 400,
                "cycle_culture_jours": 35,
                "duree_avant_recolte": 35,
                "periode_recolte": "Toute l'année",
            },
            {
                "nom": "Oseille de Guinée (Bissap)",
                "description": "Plante à calices pour boisson et feuilles en sauce. Hibiscus sabdariffa, culture emblématique.",
                "saison": "Hivernage",
                "prix_par_kg": 600,
                "rendement_moyen": 1500,
                "rendement_potentiel_max": 3000,
                "besoin_eau_mm": 500,
                "cycle_culture_jours": 150,
                "duree_avant_recolte": 150,
                "periode_recolte": "Novembre - Janvier",
            },
            {
                "nom": "Moringa",
                "description": "Arbre miracle. Feuilles très nutritives (protéines, vitamines). Croissance rapide, résistant à la sécheresse.",
                "saison": "Toute l'année",
                "prix_par_kg": 800,
                "rendement_moyen": 5000,
                "rendement_potentiel_max": 10000,
                "besoin_eau_mm": 400,
                "cycle_culture_jours": 60,
                "duree_avant_recolte": 60,
                "periode_recolte": "Toute l'année (récoltes multiples)",
            },

            # ============================================================
            #  CULTURES DE RENTE / OLÉAGINEUSES
            # ============================================================
            {
                "nom": "Coton",
                "description": "Culture de rente majeure au Mali, Burkina Faso, Côte d'Ivoire. Fibre textile et huile de graines.",
                "saison": "Hivernage",
                "prix_par_kg": 280,
                "rendement_moyen": 1200,
                "rendement_potentiel_max": 2000,
                "besoin_eau_mm": 700,
                "cycle_culture_jours": 160,
                "duree_avant_recolte": 160,
                "periode_recolte": "Octobre - Décembre",
            },
            {
                "nom": "Palmier à huile",
                "description": "Arbre oléagineux majeur en zone forestière. Huile de palme et palmiste. Culture pérenne.",
                "saison": "Pérenne",
                "prix_par_kg": 250,
                "rendement_moyen": 15000,
                "rendement_potentiel_max": 25000,
                "besoin_eau_mm": 1800,
                "cycle_culture_jours": 1095,
                "duree_avant_recolte": 1095,
                "periode_recolte": "Toute l'année (après 3-4 ans)",
            },
            {
                "nom": "Cacao",
                "description": "Culture d'export phare de la Côte d'Ivoire (1er mondial) et du Ghana. Forêt tropicale humide.",
                "saison": "Pérenne",
                "prix_par_kg": 1500,
                "rendement_moyen": 500,
                "rendement_potentiel_max": 1200,
                "besoin_eau_mm": 1500,
                "cycle_culture_jours": 1095,
                "duree_avant_recolte": 1095,
                "periode_recolte": "Octobre - Mars (récolte principale)",
            },
            {
                "nom": "Café",
                "description": "Robusta principalement, cultivé en Côte d'Ivoire, Guinée, Togo. Zones de forêt humide.",
                "saison": "Pérenne",
                "prix_par_kg": 1200,
                "rendement_moyen": 600,
                "rendement_potentiel_max": 1500,
                "besoin_eau_mm": 1500,
                "cycle_culture_jours": 1460,
                "duree_avant_recolte": 1460,
                "periode_recolte": "Novembre - Février",
            },
            {
                "nom": "Karité",
                "description": "Arbre endémique du Sahel. Noix pour beurre cosmétique et alimentaire. Cueillette et plantations.",
                "saison": "Pérenne",
                "prix_par_kg": 500,
                "rendement_moyen": 3000,
                "rendement_potentiel_max": 5000,
                "besoin_eau_mm": 800,
                "cycle_culture_jours": 5475,
                "duree_avant_recolte": 5475,
                "periode_recolte": "Juin - Septembre",
            },
            {
                "nom": "Sésame",
                "description": "Oléagineuse d'export à forte valeur. Cultivée au Burkina Faso, Mali, Sénégal, Niger.",
                "saison": "Hivernage",
                "prix_par_kg": 700,
                "rendement_moyen": 500,
                "rendement_potentiel_max": 1000,
                "besoin_eau_mm": 400,
                "cycle_culture_jours": 90,
                "duree_avant_recolte": 90,
                "periode_recolte": "Octobre - Novembre",
            },
            {
                "nom": "Tournesol",
                "description": "Oléagineuse émergente en Afrique de l'Ouest. Potentiel en zone soudanienne.",
                "saison": "Hivernage",
                "prix_par_kg": 350,
                "rendement_moyen": 1200,
                "rendement_potentiel_max": 2500,
                "besoin_eau_mm": 500,
                "cycle_culture_jours": 100,
                "duree_avant_recolte": 100,
                "periode_recolte": "Septembre - Octobre",
            },

            # ============================================================
            #  FRUITS
            # ============================================================
            {
                "nom": "Mangue",
                "description": "Fruit majeur d'Afrique de l'Ouest. Export frais et transformé (séché, jus). Mali, Sénégal, Guinée, Burkina.",
                "saison": "Pérenne",
                "prix_par_kg": 300,
                "rendement_moyen": 8000,
                "rendement_potentiel_max": 15000,
                "besoin_eau_mm": 800,
                "cycle_culture_jours": 1825,
                "duree_avant_recolte": 1825,
                "periode_recolte": "Mai - Août",
            },
            {
                "nom": "Banane",
                "description": "Fruit et légume (banane plantain). Cultivé en zone humide : Guinée, Côte d'Ivoire, Ghana.",
                "saison": "Toute l'année",
                "prix_par_kg": 250,
                "rendement_moyen": 20000,
                "rendement_potentiel_max": 40000,
                "besoin_eau_mm": 1500,
                "cycle_culture_jours": 365,
                "duree_avant_recolte": 365,
                "periode_recolte": "Toute l'année",
            },
            {
                "nom": "Banane plantain",
                "description": "Aliment de base en zone forestière. Frit (alloco), bouilli, pilé (foufou).",
                "saison": "Toute l'année",
                "prix_par_kg": 300,
                "rendement_moyen": 12000,
                "rendement_potentiel_max": 25000,
                "besoin_eau_mm": 1500,
                "cycle_culture_jours": 365,
                "duree_avant_recolte": 365,
                "periode_recolte": "Toute l'année",
            },
            {
                "nom": "Ananas",
                "description": "Fruit d'export cultivé en Côte d'Ivoire, Ghana, Guinée. Variétés Cayenne lisse et MD2.",
                "saison": "Toute l'année",
                "prix_par_kg": 350,
                "rendement_moyen": 40000,
                "rendement_potentiel_max": 70000,
                "besoin_eau_mm": 1200,
                "cycle_culture_jours": 540,
                "duree_avant_recolte": 540,
                "periode_recolte": "Toute l'année (18 mois)",
            },
            {
                "nom": "Papaye",
                "description": "Fruit tropical à croissance rapide. Riche en vitamines A et C. Culture périurbaine.",
                "saison": "Toute l'année",
                "prix_par_kg": 250,
                "rendement_moyen": 30000,
                "rendement_potentiel_max": 50000,
                "besoin_eau_mm": 1200,
                "cycle_culture_jours": 270,
                "duree_avant_recolte": 270,
                "periode_recolte": "Toute l'année (après 9 mois)",
            },
            {
                "nom": "Agrumes (Orange)",
                "description": "Oranges, mandarines, citrons. Cultivés dans les Niayes, vallée du fleuve, zone soudanienne.",
                "saison": "Pérenne",
                "prix_par_kg": 350,
                "rendement_moyen": 15000,
                "rendement_potentiel_max": 30000,
                "besoin_eau_mm": 900,
                "cycle_culture_jours": 1095,
                "duree_avant_recolte": 1095,
                "periode_recolte": "Novembre - Mars",
            },
            {
                "nom": "Citron",
                "description": "Agrume très demandé pour la cuisine et les boissons. Zone des Niayes et bassins irrigués.",
                "saison": "Pérenne",
                "prix_par_kg": 400,
                "rendement_moyen": 12000,
                "rendement_potentiel_max": 25000,
                "besoin_eau_mm": 800,
                "cycle_culture_jours": 1095,
                "duree_avant_recolte": 1095,
                "periode_recolte": "Toute l'année",
            },
            {
                "nom": "Noix de coco",
                "description": "Palmier côtier. Coprah, eau de coco, huile. Grand-Bassam, littoral ouest-africain.",
                "saison": "Pérenne",
                "prix_par_kg": 200,
                "rendement_moyen": 6000,
                "rendement_potentiel_max": 12000,
                "besoin_eau_mm": 1500,
                "cycle_culture_jours": 2190,
                "duree_avant_recolte": 2190,
                "periode_recolte": "Toute l'année (après 6 ans)",
            },
            {
                "nom": "Noix de cajou (Anacarde)",
                "description": "Noix d'export majeure. Côte d'Ivoire, Guinée-Bissau, Sénégal, Bénin. Forte croissance.",
                "saison": "Pérenne",
                "prix_par_kg": 1000,
                "rendement_moyen": 800,
                "rendement_potentiel_max": 1500,
                "besoin_eau_mm": 600,
                "cycle_culture_jours": 1095,
                "duree_avant_recolte": 1095,
                "periode_recolte": "Mars - Juin",
            },
            {
                "nom": "Pastèque",
                "description": "Cucurbitacée très cultivée en saison sèche et hivernage. Forte demande locale.",
                "saison": "Hivernage / Contre-saison",
                "prix_par_kg": 150,
                "rendement_moyen": 25000,
                "rendement_potentiel_max": 45000,
                "besoin_eau_mm": 500,
                "cycle_culture_jours": 80,
                "duree_avant_recolte": 80,
                "periode_recolte": "Toute l'année",
            },
            {
                "nom": "Melon",
                "description": "Fruit de contre-saison cultivé dans les Niayes pour le marché local et l'export.",
                "saison": "Contre-saison",
                "prix_par_kg": 350,
                "rendement_moyen": 18000,
                "rendement_potentiel_max": 30000,
                "besoin_eau_mm": 500,
                "cycle_culture_jours": 75,
                "duree_avant_recolte": 75,
                "periode_recolte": "Décembre - Avril",
            },
            {
                "nom": "Goyave",
                "description": "Fruit tropical riche en vitamine C. Arbuste productif, culture familiale ou semi-commerciale.",
                "saison": "Pérenne",
                "prix_par_kg": 300,
                "rendement_moyen": 10000,
                "rendement_potentiel_max": 20000,
                "besoin_eau_mm": 800,
                "cycle_culture_jours": 730,
                "duree_avant_recolte": 730,
                "periode_recolte": "Août - Novembre",
            },
            {
                "nom": "Avocat",
                "description": "Fruit gras riche en nutriments. Culture émergente dans les zones humides et d'altitude.",
                "saison": "Pérenne",
                "prix_par_kg": 600,
                "rendement_moyen": 8000,
                "rendement_potentiel_max": 15000,
                "besoin_eau_mm": 1200,
                "cycle_culture_jours": 1460,
                "duree_avant_recolte": 1460,
                "periode_recolte": "Juin - Septembre",
            },
            {
                "nom": "Fruit de la passion (Maracuja)",
                "description": "Liane fruitière émergente. Jus très apprécié. Culture en essor en Côte d'Ivoire et Guinée.",
                "saison": "Pérenne",
                "prix_par_kg": 700,
                "rendement_moyen": 12000,
                "rendement_potentiel_max": 20000,
                "besoin_eau_mm": 1000,
                "cycle_culture_jours": 365,
                "duree_avant_recolte": 365,
                "periode_recolte": "Toute l'année (après 1 an)",
            },
            {
                "nom": "Datte",
                "description": "Fruit du palmier dattier. Cultivé en zone saharienne et sahélienne (Mauritanie, nord Mali, Niger).",
                "saison": "Pérenne",
                "prix_par_kg": 800,
                "rendement_moyen": 5000,
                "rendement_potentiel_max": 10000,
                "besoin_eau_mm": 300,
                "cycle_culture_jours": 1825,
                "duree_avant_recolte": 1825,
                "periode_recolte": "Octobre - Décembre",
            },
            {
                "nom": "Tamarin",
                "description": "Fruit du tamarinier pour jus, confiserie et cuisine. Arbre sahélien très répandu.",
                "saison": "Pérenne",
                "prix_par_kg": 400,
                "rendement_moyen": 3000,
                "rendement_potentiel_max": 8000,
                "besoin_eau_mm": 600,
                "cycle_culture_jours": 2555,
                "duree_avant_recolte": 2555,
                "periode_recolte": "Décembre - Mars",
            },
            {
                "nom": "Baobab (fruit - pain de singe)",
                "description": "Fruit du baobab, riche en vitamine C. Poudre et jus (bouye). Cueillette et valorisation.",
                "saison": "Pérenne",
                "prix_par_kg": 600,
                "rendement_moyen": 2000,
                "rendement_potentiel_max": 5000,
                "besoin_eau_mm": 400,
                "cycle_culture_jours": 3650,
                "duree_avant_recolte": 3650,
                "periode_recolte": "Novembre - Février",
            },

            # ============================================================
            #  ÉPICES & CONDIMENTS
            # ============================================================
            {
                "nom": "Gingembre",
                "description": "Rhizome épicé très utilisé en cuisine et médecine traditionnelle. Culture en zone humide.",
                "saison": "Hivernage",
                "prix_par_kg": 800,
                "rendement_moyen": 8000,
                "rendement_potentiel_max": 15000,
                "besoin_eau_mm": 1500,
                "cycle_culture_jours": 240,
                "duree_avant_recolte": 240,
                "periode_recolte": "Novembre - Janvier",
            },
            {
                "nom": "Curcuma",
                "description": "Rhizome cousin du gingembre. Épice et colorant naturel. Culture émergente.",
                "saison": "Hivernage",
                "prix_par_kg": 1000,
                "rendement_moyen": 6000,
                "rendement_potentiel_max": 12000,
                "besoin_eau_mm": 1500,
                "cycle_culture_jours": 270,
                "duree_avant_recolte": 270,
                "periode_recolte": "Décembre - Février",
            },
            {
                "nom": "Poivre de Guinée (Maniguette)",
                "description": "Épice endémique d'Afrique de l'Ouest. Graines aromatiques, forte valeur à l'export.",
                "saison": "Pérenne",
                "prix_par_kg": 3000,
                "rendement_moyen": 500,
                "rendement_potentiel_max": 1000,
                "besoin_eau_mm": 1500,
                "cycle_culture_jours": 730,
                "duree_avant_recolte": 730,
                "periode_recolte": "Septembre - Décembre",
            },

            # ============================================================
            #  CULTURES INDUSTRIELLES
            # ============================================================
            {
                "nom": "Canne à sucre",
                "description": "Culture industrielle irriguée. Sucreries au Sénégal (CSS), Mali (Sukala), Côte d'Ivoire.",
                "saison": "Toute l'année (irrigué)",
                "prix_par_kg": 80,
                "rendement_moyen": 60000,
                "rendement_potentiel_max": 120000,
                "besoin_eau_mm": 1800,
                "cycle_culture_jours": 365,
                "duree_avant_recolte": 365,
                "periode_recolte": "Novembre - Mai",
            },
            {
                "nom": "Tabac",
                "description": "Culture industrielle de zone soudanienne. Produit pour le marché national.",
                "saison": "Hivernage",
                "prix_par_kg": 600,
                "rendement_moyen": 1500,
                "rendement_potentiel_max": 2500,
                "besoin_eau_mm": 500,
                "cycle_culture_jours": 120,
                "duree_avant_recolte": 120,
                "periode_recolte": "Octobre - Décembre",
            },
            {
                "nom": "Hévéa (Caoutchouc)",
                "description": "Arbre à latex cultivé en Côte d'Ivoire, Libéria, Ghana. Culture pérenne d'export.",
                "saison": "Pérenne",
                "prix_par_kg": 400,
                "rendement_moyen": 1500,
                "rendement_potentiel_max": 2500,
                "besoin_eau_mm": 2000,
                "cycle_culture_jours": 2190,
                "duree_avant_recolte": 2190,
                "periode_recolte": "Toute l'année (saignée après 6 ans)",
            },

            # ============================================================
            #  CULTURES ÉMERGENTES / NOUVELLES
            # ============================================================
            {
                "nom": "Quinoa",
                "description": "Pseudo-céréale andine riche en protéines. Essais prometteurs au Sénégal et Burkina Faso.",
                "saison": "Contre-saison",
                "prix_par_kg": 1500,
                "rendement_moyen": 1000,
                "rendement_potentiel_max": 2500,
                "besoin_eau_mm": 350,
                "cycle_culture_jours": 90,
                "duree_avant_recolte": 90,
                "periode_recolte": "Février - Avril",
            },
            {
                "nom": "Spiruline",
                "description": "Micro-algue super-nutritive cultivée en bassin. Riche en protéines, fer, vitamines. Production au Burkina, Mali, Niger.",
                "saison": "Toute l'année",
                "prix_par_kg": 10000,
                "rendement_moyen": 8000,
                "rendement_potentiel_max": 15000,
                "besoin_eau_mm": None,
                "cycle_culture_jours": 30,
                "duree_avant_recolte": 30,
                "periode_recolte": "Toute l'année (récolte continue)",
            },
            {
                "nom": "Jatropha (Pourghère)",
                "description": "Plante oléagineuse pour biocarburant. Résistante à la sécheresse. Haies vives et production d'huile.",
                "saison": "Pérenne",
                "prix_par_kg": 200,
                "rendement_moyen": 2000,
                "rendement_potentiel_max": 5000,
                "besoin_eau_mm": 500,
                "cycle_culture_jours": 730,
                "duree_avant_recolte": 730,
                "periode_recolte": "Octobre - Décembre",
            },
            {
                "nom": "Stevia",
                "description": "Plante sucrante naturelle sans calories. Culture émergente en zone tropicale.",
                "saison": "Toute l'année",
                "prix_par_kg": 5000,
                "rendement_moyen": 2000,
                "rendement_potentiel_max": 4000,
                "besoin_eau_mm": 600,
                "cycle_culture_jours": 90,
                "duree_avant_recolte": 90,
                "periode_recolte": "Toute l'année (récoltes multiples)",
            },
            {
                "nom": "Champignons (Pleurotes)",
                "description": "Champignons cultivés en milieu contrôlé. Forte demande urbaine. Valorisation de déchets agricoles.",
                "saison": "Toute l'année",
                "prix_par_kg": 2000,
                "rendement_moyen": 10000,
                "rendement_potentiel_max": 20000,
                "besoin_eau_mm": None,
                "cycle_culture_jours": 30,
                "duree_avant_recolte": 30,
                "periode_recolte": "Toute l'année",
            },
            {
                "nom": "Aloe Vera",
                "description": "Plante succulente à usage cosmétique, médicinal et alimentaire. Très résistante à la sécheresse.",
                "saison": "Toute l'année",
                "prix_par_kg": 500,
                "rendement_moyen": 20000,
                "rendement_potentiel_max": 40000,
                "besoin_eau_mm": 300,
                "cycle_culture_jours": 365,
                "duree_avant_recolte": 365,
                "periode_recolte": "Toute l'année (après 1 an)",
            },
            {
                "nom": "Vanille",
                "description": "Orchidée grimpante. Essais en zone humide (Guinée forestière, sud Côte d'Ivoire). Très haute valeur.",
                "saison": "Pérenne",
                "prix_par_kg": 25000,
                "rendement_moyen": 200,
                "rendement_potentiel_max": 600,
                "besoin_eau_mm": 2000,
                "cycle_culture_jours": 1095,
                "duree_avant_recolte": 1095,
                "periode_recolte": "Avril - Juin",
            },
            {
                "nom": "Poivre noir",
                "description": "Liane épicée cultivée en zone forestière humide. Produit de niche à forte valeur.",
                "saison": "Pérenne",
                "prix_par_kg": 4000,
                "rendement_moyen": 1500,
                "rendement_potentiel_max": 3000,
                "besoin_eau_mm": 2000,
                "cycle_culture_jours": 1095,
                "duree_avant_recolte": 1095,
                "periode_recolte": "Janvier - Mars",
            },
            {
                "nom": "Avocat Hass",
                "description": "Variété premium pour l'export. Culture émergente en altitude et zone humide d'Afrique de l'Ouest.",
                "saison": "Pérenne",
                "prix_par_kg": 1000,
                "rendement_moyen": 10000,
                "rendement_potentiel_max": 18000,
                "besoin_eau_mm": 1200,
                "cycle_culture_jours": 1460,
                "duree_avant_recolte": 1460,
                "periode_recolte": "Mars - Juillet",
            },
            {
                "nom": "Fraise",
                "description": "Fruit de niche cultivé en contre-saison dans les zones fraîches (Niayes, Fouta Djallon).",
                "saison": "Contre-saison",
                "prix_par_kg": 2000,
                "rendement_moyen": 15000,
                "rendement_potentiel_max": 30000,
                "besoin_eau_mm": 600,
                "cycle_culture_jours": 90,
                "duree_avant_recolte": 90,
                "periode_recolte": "Décembre - Mars",
            },
            {
                "nom": "Noix de macadamia",
                "description": "Noix premium à très haute valeur. Culture émergente en zone subhumide d'Afrique de l'Ouest.",
                "saison": "Pérenne",
                "prix_par_kg": 5000,
                "rendement_moyen": 3000,
                "rendement_potentiel_max": 6000,
                "besoin_eau_mm": 1000,
                "cycle_culture_jours": 1825,
                "duree_avant_recolte": 1825,
                "periode_recolte": "Mars - Juin",
            },
            {
                "nom": "Chia",
                "description": "Graine riche en oméga-3 et fibres. Essais en cours en zone soudanienne.",
                "saison": "Hivernage",
                "prix_par_kg": 2000,
                "rendement_moyen": 600,
                "rendement_potentiel_max": 1200,
                "besoin_eau_mm": 400,
                "cycle_culture_jours": 100,
                "duree_avant_recolte": 100,
                "periode_recolte": "Octobre - Novembre",
            },
            {
                "nom": "Pitaya (Fruit du dragon)",
                "description": "Cactus fruitier spectaculaire. Culture émergente en zone sèche irriguée. Fort potentiel export.",
                "saison": "Pérenne",
                "prix_par_kg": 2500,
                "rendement_moyen": 15000,
                "rendement_potentiel_max": 25000,
                "besoin_eau_mm": 600,
                "cycle_culture_jours": 365,
                "duree_avant_recolte": 365,
                "periode_recolte": "Juin - Novembre",
            },
            {
                "nom": "Neem",
                "description": "Arbre médicinal et insecticide naturel. Huile de neem, tourteau. Omniprésent en zone sahélienne.",
                "saison": "Pérenne",
                "prix_par_kg": 300,
                "rendement_moyen": 4000,
                "rendement_potentiel_max": 8000,
                "besoin_eau_mm": 400,
                "cycle_culture_jours": 1825,
                "duree_avant_recolte": 1825,
                "periode_recolte": "Juillet - Septembre",
            },
            {
                "nom": "Citronnelle",
                "description": "Herbe aromatique pour tisanes, huile essentielle et cuisine. Pousse facilement en zone tropicale.",
                "saison": "Toute l'année",
                "prix_par_kg": 400,
                "rendement_moyen": 5000,
                "rendement_potentiel_max": 10000,
                "besoin_eau_mm": 800,
                "cycle_culture_jours": 120,
                "duree_avant_recolte": 120,
                "periode_recolte": "Toute l'année",
            },
            {
                "nom": "Menthe",
                "description": "Herbe aromatique pour le thé et la cuisine. Culture maraîchère à cycle rapide.",
                "saison": "Toute l'année",
                "prix_par_kg": 500,
                "rendement_moyen": 4000,
                "rendement_potentiel_max": 8000,
                "besoin_eau_mm": 600,
                "cycle_culture_jours": 45,
                "duree_avant_recolte": 45,
                "periode_recolte": "Toute l'année",
            },
            {
                "nom": "Basilic africain",
                "description": "Herbe aromatique traditionnelle. Usage culinaire et médicinal. Culture facile.",
                "saison": "Toute l'année",
                "prix_par_kg": 500,
                "rendement_moyen": 3000,
                "rendement_potentiel_max": 6000,
                "besoin_eau_mm": 500,
                "cycle_culture_jours": 40,
                "duree_avant_recolte": 40,
                "periode_recolte": "Toute l'année",
            },

            # ============================================================
            #  FOURRAGÈRES & COUVERTURE
            # ============================================================
            {
                "nom": "Niébé fourrager",
                "description": "Variété de niébé cultivée pour le fourrage animal. Fixation d'azote et couverture du sol.",
                "saison": "Hivernage",
                "prix_par_kg": 200,
                "rendement_moyen": 3000,
                "rendement_potentiel_max": 6000,
                "besoin_eau_mm": 350,
                "cycle_culture_jours": 60,
                "duree_avant_recolte": 60,
                "periode_recolte": "Septembre - Octobre",
            },
            {
                "nom": "Mucuna",
                "description": "Légumineuse de couverture et fourrage. Améliore la fertilité du sol. Agriculture de conservation.",
                "saison": "Hivernage",
                "prix_par_kg": 300,
                "rendement_moyen": 2000,
                "rendement_potentiel_max": 4000,
                "besoin_eau_mm": 500,
                "cycle_culture_jours": 120,
                "duree_avant_recolte": 120,
                "periode_recolte": "Octobre - Décembre",
            },
            {
                "nom": "Brachiaria",
                "description": "Graminée fourragère tropicale. Excellente pour le pâturage et la lutte contre l'érosion.",
                "saison": "Toute l'année",
                "prix_par_kg": 150,
                "rendement_moyen": 15000,
                "rendement_potentiel_max": 25000,
                "besoin_eau_mm": 800,
                "cycle_culture_jours": 90,
                "duree_avant_recolte": 90,
                "periode_recolte": "Toute l'année (coupes multiples)",
            },
        ]
